#!/usr/bin/env bash
# ==============================================================================
# installer/steps/03_config.sh — Generate config.env
# ==============================================================================
# Writes all wizard-collected values to config.env with inline documentation.
# An existing config.env is backed up with a timestamp before overwriting.
# ==============================================================================

generate_config() {
    print_section "Generating config.env"

    _backup_existing_config
    _write_config_file
    chmod 600 "${CONFIG_FILE}"
    ok "config.env written (permissions: 600)"
    INSTALLED_COMPONENTS+=("config.env")
    ROLLBACK_ACTIONS+=("rm -f ${CONFIG_FILE} 2>/dev/null || true")
}

# ── Private helpers ────────────────────────────────────────────────────────────

_backup_existing_config() {
    [[ -f "${CONFIG_FILE}" ]] || return 0
    local backup_name="${CONFIG_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
    cp "${CONFIG_FILE}" "${backup_name}"
    ok "Existing config backed up to: ${backup_name}"
}

_write_config_file() {
    local map_pool_str
    map_pool_str="$(IFS=','; echo "${SELECTED_MAPS[*]}")"
    local match_port_end=$(( MATCH_PORT_START + MATCH_SLOTS - 1 ))
    local notification_backend="none"
    [[ -n "${DISCORD_WEBHOOK_URL}" ]] && notification_backend="discord"

    cat > "${CONFIG_FILE}" << CONFIG_EOF
# ============================================
# CS:GO Matchmaking System - Configuration
# ============================================
# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')
# To re-run the wizard: sudo ./install.sh
# WARNING: This file contains secrets. Do not commit to version control.

# --- Database ---
# Host of the MySQL/MariaDB server
DB_HOST=${DB_HOST}
# MySQL port (default 3306)
DB_PORT=${DB_PORT}
# Database user for the matchmaking system
DB_USER=csgo_mm
# Database password (auto-generated during install)
DB_PASS=${DB_PASS}
# Database name
DB_NAME=csgo_matchmaking

# --- Server ---
# Public IP address of your server (auto-detected by install.sh)
SERVER_IP=${SERVER_IP}
# Lobby server address (IP:PORT players connect to)
LOBBY_IP=${SERVER_IP}
# Lobby server port
LOBBY_PORT=${LOBBY_PORT}
# Match server port range
MATCH_PORT_START=${MATCH_PORT_START}
MATCH_PORT_END=${match_port_end}
MATCH_SLOTS=${MATCH_SLOTS}
# RCON password for server communication
RCON_PASSWORD=${RCON_PASSWORD}

# --- GSLT ---
# Lobby server Game Server Login Token
LOBBY_GSLT=${LOBBY_GSLT}

# --- Matchmaking ---
# How often the matchmaker polls the queue (seconds)
POLL_INTERVAL=2.0
# Players per team (default 5 for 5v5)
PLAYERS_PER_TEAM=${PLAYERS_PER_TEAM}
# Initial max ELO difference between players in a match
MAX_ELO_SPREAD=${MAX_ELO_SPREAD}
# Widen ELO spread by this amount every INTERVAL seconds
ELO_SPREAD_INCREASE_INTERVAL=60
ELO_SPREAD_INCREASE_AMOUNT=50
# Ready check timeout (seconds)
READY_CHECK_TIMEOUT=${READY_CHECK_TIMEOUT}
# Warmup timeout - cancel match if not all players connect (seconds)
WARMUP_TIMEOUT=180
# Matches needed before ELO stabilizes (placement period)
MIN_PLACEMENT_MATCHES=10

# --- ELO ---
# K-factor for standard players (determines ELO volatility)
ELO_K_FACTOR=32
# K-factor for new players (higher = more volatile during placements)
ELO_K_FACTOR_NEW=64
# Starting ELO for new players
ELO_DEFAULT=1000

# --- Map Pool ---
# Comma-separated list of maps available for matchmaking
MAP_POOL=${map_pool_str}

# --- Backends (modular architecture) ---
# Queue backend: mysql (default) | redis (future)
QUEUE_BACKEND=mysql
# Server orchestration: docker (default) | kubernetes (future)
SERVER_BACKEND=docker
# Notification system: discord | slack | none
NOTIFICATION_BACKEND=${notification_backend}
# Ranking algorithm: elo (default) | glicko2 (future)
RANKING_BACKEND=elo

# --- Docker ---
# Docker image for match servers (built by install.sh)
DOCKER_IMAGE=csgo-match-server:latest
# Docker network mode (host recommended for game servers on Linux)
DOCKER_NETWORK=host

# --- Web Panel ---
WEB_HOST=0.0.0.0
WEB_PORT=${WEB_PORT}
# Flask secret key (generated by install.sh — change in production)
SECRET_KEY=${FLASK_SECRET_KEY}

# --- Discord (optional) ---
# Leave empty to disable Discord notifications
DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}

# --- Levels Ranks ---
# Table name used by Levels Ranks plugin (default: lvl_base)
LR_TABLE_NAME=lvl_base
CONFIG_EOF
}
