#!/usr/bin/env bash
# =============================================================================
# entrypoint.sh — CS:GO Match Server Entrypoint
#
# Generates runtime configuration files from environment variables injected
# by the Python matchmaker, then hands off to the base cm2network entrypoint.
#
# Generated files:
#   addons/sourcemod/configs/databases.cfg  — DB connection for SourceMod
#   cfg/mm_match.cfg                        — Match token, ID, lobby IP
#   cfg/mm_whitelist.cfg                    — Allowed SteamIDs for this match
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------
log()  { echo "[MM-ENTRY] $*"; }
warn() { echo "[MM-ENTRY][WARN] $*" >&2; }
die()  { echo "[MM-ENTRY][ERROR] $*" >&2; exit 1; }

log "CS:GO Match Server entrypoint starting..."

# ---------------------------------------------------------------------------
# Resolve the CS:GO data directory. The cm2network image installs the
# dedicated server under /home/steam/csgo-dedicated.
# ---------------------------------------------------------------------------
CSGO_DIR="/home/steam/csgo-dedicated/csgo"
SM_CONFIGS="${CSGO_DIR}/addons/sourcemod/configs"
CFG_DIR="${CSGO_DIR}/cfg"

# Sanity-check that the game directory exists (it should after the base image
# runs SteamCMD on first boot, but entrypoint might run before that).
# We generate the config files unconditionally; if the dir doesn't yet exist
# the base entrypoint will create it before the server launches.
mkdir -p "${SM_CONFIGS}" "${CFG_DIR}"

# ---------------------------------------------------------------------------
# 1. Read environment variables with safe defaults
# ---------------------------------------------------------------------------

# Database connection
MM_DB_HOST="${MM_DB_HOST:-127.0.0.1}"
MM_DB_USER="${MM_DB_USER:-csgo_mm}"
MM_DB_PASS="${MM_DB_PASS:-changeme}"
MM_DB_NAME="${MM_DB_NAME:-csgo_matchmaking}"

# Match identity
MM_MATCH_TOKEN="${MM_MATCH_TOKEN:-}"
MM_MATCH_ID="${MM_MATCH_ID:-0}"
MM_LOBBY_IP="${MM_LOBBY_IP:-}"

# Team rosters (comma-separated SteamIDs)
MM_TEAM1_STEAMIDS="${MM_TEAM1_STEAMIDS:-}"
MM_TEAM2_STEAMIDS="${MM_TEAM2_STEAMIDS:-}"

# Warn about missing critical values but don't abort — the plugin will
# handle a missing token/ID gracefully rather than crashing the container.
[[ -z "${MM_MATCH_TOKEN}" ]] && warn "MM_MATCH_TOKEN is not set!"
[[ -z "${MM_MATCH_ID}" || "${MM_MATCH_ID}" == "0" ]] && warn "MM_MATCH_ID is not set or is 0!"
[[ -z "${MM_LOBBY_IP}" ]] && warn "MM_LOBBY_IP is not set — players won't be redirected after match."
[[ -z "${MM_TEAM1_STEAMIDS}" ]] && warn "MM_TEAM1_STEAMIDS is empty — no team 1 whitelist!"
[[ -z "${MM_TEAM2_STEAMIDS}" ]] && warn "MM_TEAM2_STEAMIDS is empty — no team 2 whitelist!"

log "DB: ${MM_DB_USER}@${MM_DB_HOST}/${MM_DB_NAME}"
log "Match ID: ${MM_MATCH_ID}  Token: ${MM_MATCH_TOKEN:0:8}..."
log "Lobby: ${MM_LOBBY_IP}"

# ---------------------------------------------------------------------------
# 2. Generate addons/sourcemod/configs/databases.cfg
#    SourceMod requires this file to exist for the dbi.mysql extension.
#    Both "csgo_matchmaking" and "levels_ranks" entries point to the same DB
#    so that both plugins share a connection pool to the same backend.
# ---------------------------------------------------------------------------
DATABASES_CFG="${SM_CONFIGS}/databases.cfg"
log "Writing ${DATABASES_CFG} ..."

cat > "${DATABASES_CFG}" << EOF
"Databases"
{
    // Default driver — override per-entry if needed
    "default"
    {
        "driver"    "default"
    }

    // Primary matchmaking database — used by csgo_mm_match.sp
    "csgo_matchmaking"
    {
        "driver"    "mysql"
        "host"      "${MM_DB_HOST}"
        "database"  "${MM_DB_NAME}"
        "user"      "${MM_DB_USER}"
        "pass"      "${MM_DB_PASS}"
        "port"      "3306"
    }

    // Levels Ranks plugin — points to same DB (mm_ and lvl_base tables coexist)
    "levels_ranks"
    {
        "driver"    "mysql"
        "host"      "${MM_DB_HOST}"
        "database"  "${MM_DB_NAME}"
        "user"      "${MM_DB_USER}"
        "pass"      "${MM_DB_PASS}"
        "port"      "3306"
    }
}
EOF

log "databases.cfg written."

# ---------------------------------------------------------------------------
# 3. Generate cfg/mm_match.cfg
#    Loaded by server.cfg via "exec mm_match.cfg".
#    Defines ConVars that the SourceMod plugin reads on plugin start.
# ---------------------------------------------------------------------------
MM_MATCH_CFG="${CFG_DIR}/mm_match.cfg"
log "Writing ${MM_MATCH_CFG} ..."

cat > "${MM_MATCH_CFG}" << EOF
// Auto-generated by entrypoint.sh — do not edit manually.
// Match-specific configuration injected by the Python matchmaker.

mm_match_token     "${MM_MATCH_TOKEN}"
mm_match_id        "${MM_MATCH_ID}"
mm_lobby_ip        "${MM_LOBBY_IP}"
mm_team1_steamids  "${MM_TEAM1_STEAMIDS}"
mm_team2_steamids  "${MM_TEAM2_STEAMIDS}"
EOF

log "mm_match.cfg written."

# ---------------------------------------------------------------------------
# 4. Generate cfg/mm_whitelist.cfg
#    Contains one "mm_allowed_steamid" entry per whitelisted player.
#    Loaded by the plugin at startup to build the in-memory roster.
#
#    Format (SourceMod ConVar convention — plugin reads file directly):
#        mm_allowed_steamid "STEAM_1:0:12345678"
#        mm_allowed_steamid "STEAM_1:1:87654321"
#        ...
# ---------------------------------------------------------------------------
MM_WHITELIST_CFG="${CFG_DIR}/mm_whitelist.cfg"
log "Writing ${MM_WHITELIST_CFG} ..."

{
    echo "// Auto-generated by entrypoint.sh — do not edit manually."
    echo "// Whitelisted SteamIDs for match ${MM_MATCH_ID}."
    echo ""

    # Process team 1
    if [[ -n "${MM_TEAM1_STEAMIDS}" ]]; then
        echo "// Team 1"
        # Replace commas with newlines, strip whitespace, emit one line per ID
        while IFS= read -r steamid; do
            # Strip leading/trailing whitespace
            steamid="${steamid#"${steamid%%[![:space:]]*}"}"
            steamid="${steamid%"${steamid##*[![:space:]]}"}"
            [[ -n "${steamid}" ]] && echo "mm_allowed_steamid \"${steamid}\""
        done < <(tr ',' '\n' <<< "${MM_TEAM1_STEAMIDS}")
        echo ""
    fi

    # Process team 2
    if [[ -n "${MM_TEAM2_STEAMIDS}" ]]; then
        echo "// Team 2"
        while IFS= read -r steamid; do
            steamid="${steamid#"${steamid%%[![:space:]]*}"}"
            steamid="${steamid%"${steamid##*[![:space:]]}"}"
            [[ -n "${steamid}" ]] && echo "mm_allowed_steamid \"${steamid}\""
        done < <(tr ',' '\n' <<< "${MM_TEAM2_STEAMIDS}")
    fi
} > "${MM_WHITELIST_CFG}"

# Count how many SteamIDs we wrote for logging
whitelist_count=$(grep -c 'mm_allowed_steamid' "${MM_WHITELIST_CFG}" 2>/dev/null || echo 0)
log "mm_whitelist.cfg written with ${whitelist_count} SteamID(s)."

# ---------------------------------------------------------------------------
# 5. Optional: log the SRCDS launch parameters for debugging
# ---------------------------------------------------------------------------
log "SRCDS_PORT=${SRCDS_PORT:-27020}"
log "SRCDS_TV_PORT=${SRCDS_TV_PORT:-27120}"
log "SRCDS_STARTMAP=${SRCDS_STARTMAP:-de_dust2}"
log "SRCDS_MAXPLAYERS=${SRCDS_MAXPLAYERS:-12}"
log "SRCDS_TICKRATE=${SRCDS_TICKRATE:-128}"

# ---------------------------------------------------------------------------
# 6. Hand off to the original cm2network base image entrypoint.
#    We use exec so the base script becomes PID 1 and receives signals
#    correctly (SIGTERM for graceful shutdown).
# ---------------------------------------------------------------------------
log "Handing off to base entrypoint: /home/steam/csgo-dedicated/entry.sh"
exec /home/steam/csgo-dedicated/entry.sh
