/**
 * csgo_mm_match.sp — CS:GO Matchmaking: Match Lifecycle Plugin
 *
 * Handles the full lifecycle of a competitive 5v5 match:
 *   • Player whitelist enforcement (SteamID-based)
 *   • Warmup phase with all-connected detection
 *   • Live-play stat tracking (kills/deaths/assists/headshots/damage/MVPs)
 *   • Match-end detection via cs_win_panel_match
 *   • Stats persisted to mm_match_players via threaded SQL
 *   • mm_matches status and score updated throughout
 *   • Post-match redirect to lobby server
 *
 * Depends on: csgo_mm.inc, dbi.mysql (SourceMod MySQL extension)
 *
 * ConVars (set via cfg/mm_match.cfg, generated by entrypoint.sh):
 *   mm_match_token  — match token string (also the server password source)
 *   mm_match_id     — integer match ID in mm_matches
 *   mm_lobby_ip     — "IP:PORT" of the lobby server for post-match redirect
 */

#include <sourcemod>
#include <sdktools>
#include <cstrike>
#include <dbi>
#include <csgo_mm>

#pragma semicolon 1
#pragma newdecls required

// ─────────────────────────────────────────────────────────────────────────────
// Plugin metadata
// ─────────────────────────────────────────────────────────────────────────────

public Plugin myinfo = {
    name        = "CS:GO MM — Match Lifecycle",
    author      = "CSGO-Matchmaking Community",
    description = "Manages a single competitive match: whitelist, stats, DB writes, redirect.",
    version     = MM_VERSION,
    url         = ""
};

// ─────────────────────────────────────────────────────────────────────────────
// Global state
// ─────────────────────────────────────────────────────────────────────────────

Database g_hDB = null;

// ConVar handles — values set by cfg/mm_match.cfg before plugin load
ConVar g_cvMatchToken;
ConVar g_cvMatchId;
ConVar g_cvLobbyIP;

// Cached plain values read from ConVars on plugin start
char g_sMatchToken[65];
int  g_iMatchId;
char g_sLobbyIP[64];

// ConVars for team rosters (comma-separated SteamIDs, set by cfg/mm_match.cfg)
ConVar g_cvTeam1SteamIDs;
ConVar g_cvTeam2SteamIDs;

// ─────────────────────────────────────────────────────────────────────────────
// Team rosters — populated from env vars via ReadTeamRostersFromEnv()
// ─────────────────────────────────────────────────────────────────────────────

// Maximum 5 per team; SteamIDs are "STEAM_X:Y:Z" (≤ 31 chars + NUL)
char g_sTeam1SteamIds[5][32];
char g_sTeam2SteamIds[5][32];
int  g_iTeam1Count = 0;
int  g_iTeam2Count = 0;

// ─────────────────────────────────────────────────────────────────────────────
// Per-client stats — reset on plugin start / map change
// ─────────────────────────────────────────────────────────────────────────────

int  g_iKills[MAXPLAYERS+1];
int  g_iDeaths[MAXPLAYERS+1];
int  g_iAssists[MAXPLAYERS+1];
int  g_iHeadshots[MAXPLAYERS+1];
int  g_iMVPs[MAXPLAYERS+1];
int  g_iDamage[MAXPLAYERS+1];
int  g_iScore[MAXPLAYERS+1];
char g_sSteamId[MAXPLAYERS+1][32];

// ─────────────────────────────────────────────────────────────────────────────
// Match state machine
// ─────────────────────────────────────────────────────────────────────────────

enum MatchState {
    MatchState_Warmup,
    MatchState_Knife,    // Knife round — winner chooses CT/T
    MatchState_Live,
    MatchState_Overtime,
    MatchState_Finished
}
MatchState g_eMatchState = MatchState_Warmup;

// Set to true once all whitelisted players have connected and gone in-game.
// Prevents the warmup-timeout from cancelling an already-live match.
bool g_bAllConnected = false;

// CS_TEAM_CT / CS_TEAM_T assignment for team1 and team2.
// Populated by querying mm_match_players on OnMapStart (or when DB is ready).
// Default: team1 starts CT (most common; overwritten if DB says otherwise).
int g_iTeam1CSTeam = CS_TEAM_CT;   // CS:GO team constant for team1
int g_iTeam2CSTeam = CS_TEAM_T;    // CS:GO team constant for team2

// Timer handles — kept so we can cancel them when they become irrelevant
Handle g_hCheckTimer    = null;
Handle g_hWarmupTimer   = null;
Handle g_hCountdownTimer = null;

// Redirect countdown seconds remaining
int g_iRedirectCountdown = 15;

// ─────────────────────────────────────────────────────────────────────────────
// Knife round
// ─────────────────────────────────────────────────────────────────────────────
int  g_iKnifeKills[MAXPLAYERS+1];  // Kills during knife round
int  g_iKnifeWinCSTeam = 0;        // CS_TEAM_CT / CS_TEAM_T that won knife (0=unknown)

// ─────────────────────────────────────────────────────────────────────────────
// Map vote (up to 5 maps from mm_map_pool)
// ─────────────────────────────────────────────────────────────────────────────
char g_sMapVoteMaps[5][64];        // Internal map names
char g_sMapVoteDisplay[5][64];     // Display names for menu
int  g_iMapVoteCount = 0;          // Number of maps fetched
int  g_iMapVotes[5];               // Vote tally per slot
bool g_bMapVoteDone = false;       // Whether vote has concluded
Handle g_hMapVoteTimer = null;     // 20-second expiry timer

// ─────────────────────────────────────────────────────────────────────────────
// Surrender vote  (index 0 = team1, index 1 = team2)
// ─────────────────────────────────────────────────────────────────────────────
bool   g_bSurrenderVote[2];        // Active vote?
int    g_iSurrenderYes[2];         // Current yes-vote count
float  g_fSurrenderCooldown[2];    // GameTime() when next vote allowed
Handle g_hSurrenderTimer[2];       // Vote expiry timers

// ─────────────────────────────────────────────────────────────────────────────
// Tactical pause  (index 0 = team1, index 1 = team2)
// ─────────────────────────────────────────────────────────────────────────────
int    g_iPausesLeft[2];           // Pauses remaining per team
bool   g_bPauseRequested[2];       // Pause requested at next freeze time
bool   g_bUnpauseReady[2];         // Team signaled ready to resume
bool   g_bPaused = false;          // Match currently paused
Handle g_hPauseTimer = null;       // Forced auto-unpause timer (60 s)

// ─────────────────────────────────────────────────────────────────────────────
// Round counter — for surrender minimum rounds check
// ─────────────────────────────────────────────────────────────────────────────
int  g_iRoundsPlayed = 0;

// ─────────────────────────────────────────────────────────────────────────────
// OnPluginStart — entry point
// ─────────────────────────────────────────────────────────────────────────────

public void OnPluginStart()
{
    // ------------------------------------------------------------------
    // Register ConVars that cfg/mm_match.cfg will set at map start.
    // We create them first so they exist before the cfg is exec'd.
    // ------------------------------------------------------------------
    g_cvMatchToken     = CreateConVar("mm_match_token",     "",  "Match token (set by entrypoint)", FCVAR_PROTECTED);
    g_cvMatchId        = CreateConVar("mm_match_id",        "0", "Match ID integer (set by entrypoint)", FCVAR_PROTECTED);
    g_cvLobbyIP        = CreateConVar("mm_lobby_ip",        "",  "Lobby server IP:PORT for post-match redirect", FCVAR_PROTECTED);
    g_cvTeam1SteamIDs  = CreateConVar("mm_team1_steamids",  "",  "Comma-separated Team 1 SteamIDs (set by entrypoint)", FCVAR_PROTECTED);
    g_cvTeam2SteamIDs  = CreateConVar("mm_team2_steamids",  "",  "Comma-separated Team 2 SteamIDs (set by entrypoint)", FCVAR_PROTECTED);

    // AutoExecConfig is NOT used here — mm_match.cfg is exec'd by server.cfg
    // which fires before this plugin's ConVars are read below.

    // ------------------------------------------------------------------
    // Hook game events
    // ------------------------------------------------------------------
    HookEvent("player_death",          Event_PlayerDeath);
    HookEvent("player_hurt",           Event_PlayerHurt);
    HookEvent("player_mvp",            Event_PlayerMVP);
    HookEvent("round_end",             Event_RoundEnd);
    HookEvent("cs_win_panel_match",    Event_MatchEnd,   EventHookMode_PostNoCopy);
    HookEvent("player_connect_full",   Event_PlayerConnectFull);
    HookEvent("player_disconnect",     Event_PlayerDisconnect, EventHookMode_Pre);

    // ------------------------------------------------------------------
    // Register chat commands
    // ------------------------------------------------------------------
    RegConsoleCmd("sm_score",     Cmd_Score,    "Show current match score");
    RegConsoleCmd("sm_ff",        Cmd_Surrender, "Call a surrender vote for your team");
    RegConsoleCmd("sm_surrender", Cmd_Surrender, "Call a surrender vote for your team");
    RegConsoleCmd("sm_report",    Cmd_Report,    "Report a player: !report <name>");
    RegConsoleCmd("sm_pause",     Cmd_Pause,     "Request tactical timeout");
    RegConsoleCmd("sm_unpause",   Cmd_Unpause,   "Signal ready to resume after a pause");

    // ------------------------------------------------------------------
    // Hook additional game events
    // ------------------------------------------------------------------
    HookEvent("round_freeze_end", Event_FreezeEnd);

    // ------------------------------------------------------------------
    // Connect to database (async — callback fires when ready)
    // ------------------------------------------------------------------
    Database.Connect(DB_Connected, MM_DB_NAME);

    // ------------------------------------------------------------------
    LogMessage("[MM-Match] Plugin started. Team rosters will be loaded from ConVars in OnMapStart.");
}

// ─────────────────────────────────────────────────────────────────────────────
// OnMapStart — fires after server.cfg (and thus mm_match.cfg) has been exec'd.
// This is the reliable point to read ConVar values.
// ─────────────────────────────────────────────────────────────────────────────

public void OnMapStart()
{
    // Read ConVar values now that cfg files have been executed
    g_cvMatchToken.GetString(g_sMatchToken, sizeof(g_sMatchToken));
    g_iMatchId = g_cvMatchId.IntValue;
    g_cvLobbyIP.GetString(g_sLobbyIP, sizeof(g_sLobbyIP));

    // Load team rosters from ConVars (set by mm_match.cfg, generated by entrypoint.sh)
    ReadTeamRostersFromConVars();

    LogMessage("[MM-Match] OnMapStart — MatchID=%d  Token=%s  Lobby=%s",
        g_iMatchId, g_sMatchToken, g_sLobbyIP);

    // Reset per-client arrays for fresh map
    ResetAllClientStats();

    // Reset match state
    g_eMatchState    = MatchState_Warmup;
    g_bAllConnected  = false;
    g_iRoundsPlayed  = 0;
    g_iKnifeWinCSTeam = 0;

    // Reset surrender state
    for (int t = 0; t < 2; t++)
    {
        g_bSurrenderVote[t]      = false;
        g_iSurrenderYes[t]       = 0;
        g_fSurrenderCooldown[t]  = 0.0;
        CancelTimerSafe(g_hSurrenderTimer[t]);
    }

    // Reset pause state
    g_iPausesLeft[0] = 1;
    g_iPausesLeft[1] = 1;
    g_bPauseRequested[0] = false;
    g_bPauseRequested[1] = false;
    g_bUnpauseReady[0]   = false;
    g_bUnpauseReady[1]   = false;
    g_bPaused            = false;
    CancelTimerSafe(g_hPauseTimer);

    // Reset map vote state
    g_iMapVoteCount = 0;
    g_bMapVoteDone  = false;
    for (int i = 0; i < 5; i++) g_iMapVotes[i] = 0;
    CancelTimerSafe(g_hMapVoteTimer);

    // Reset knife kills
    for (int i = 0; i <= MAXPLAYERS; i++) g_iKnifeKills[i] = 0;

    // Cancel any leftover timers from a previous round
    CancelTimerSafe(g_hCheckTimer);
    CancelTimerSafe(g_hWarmupTimer);
    CancelTimerSafe(g_hCountdownTimer);

    // Load warmup config immediately
    ServerCommand("exec warmup.cfg");

    // Periodic timer: fires every 5 s to check whether all players are in
    g_hCheckTimer  = CreateTimer(5.0,   Timer_CheckAllConnected, _, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);

    // Warmup timeout: if not all connected within 3 minutes, cancel match
    g_hWarmupTimer = CreateTimer(180.0, Timer_WarmupTimeout,     _, TIMER_FLAG_NO_MAPCHANGE);

    // Start map vote 3 s after map load (gives players time to spawn in warmup)
    CreateTimer(3.0, Timer_StartMapVote, _, TIMER_FLAG_NO_MAPCHANGE);

    // If DB already connected, update match status to warmup and query sides
    if (g_hDB != null && g_iMatchId > 0)
    {
        DB_SetMatchStatus(MATCH_STATUS_WARMUP);
        DB_QueryTeamSides();
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// DB_Connected — async callback for Database.Connect()
// ─────────────────────────────────────────────────────────────────────────────

public void DB_Connected(Database db, const char[] error, any data)
{
    if (db == null)
    {
        LogError("[MM-Match] Database connection failed: %s", error);
        // Non-fatal for the server process; stats simply won't be saved.
        // We still allow the match to proceed.
        return;
    }

    g_hDB = db;
    LogMessage("[MM-Match] Database connected successfully.");

    // If OnMapStart has already run and we have a match ID, set warmup status
    if (g_iMatchId > 0)
    {
        DB_SetMatchStatus(MATCH_STATUS_WARMUP);
        DB_QueryTeamSides();
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ReadTeamRostersFromConVars — parse mm_team1_steamids / mm_team2_steamids
//
// The ConVars are comma-separated SteamIDs: "STEAM_1:0:123,STEAM_1:1:456"
// They are set by cfg/mm_match.cfg which is generated by entrypoint.sh.
// Called from OnMapStart() after cfg files have been executed.
// ─────────────────────────────────────────────────────────────────────────────

void ReadTeamRostersFromConVars()
{
    char buf[512];

    // Team 1
    g_iTeam1Count = 0;
    g_cvTeam1SteamIDs.GetString(buf, sizeof(buf));
    if (buf[0] != '\0')
    {
        char parts[5][32];
        int count = ExplodeString(buf, ",", parts, sizeof(parts), sizeof(parts[]));
        g_iTeam1Count = count;
        for (int i = 0; i < count; i++)
        {
            TrimString(parts[i]);
            strcopy(g_sTeam1SteamIds[i], sizeof(g_sTeam1SteamIds[]), parts[i]);
        }
    }

    // Team 2
    g_iTeam2Count = 0;
    g_cvTeam2SteamIDs.GetString(buf, sizeof(buf));
    if (buf[0] != '\0')
    {
        char parts[5][32];
        int count = ExplodeString(buf, ",", parts, sizeof(parts), sizeof(parts[]));
        g_iTeam2Count = count;
        for (int i = 0; i < count; i++)
        {
            TrimString(parts[i]);
            strcopy(g_sTeam2SteamIds[i], sizeof(g_sTeam2SteamIds[]), parts[i]);
        }
    }

    LogMessage("[MM-Match] Team rosters loaded — Team1: %d players, Team2: %d players",
        g_iTeam1Count, g_iTeam2Count);
}

// ─────────────────────────────────────────────────────────────────────────────
// OnClientPreConnectEx — whitelist gate
//
// Called before the client fully connects. If the SteamID is not on either
// team roster, the connection is rejected with a human-readable message.
//
// NOTE: This forward requires the "Client Preferences" or the standard SM
//       "OnClientPreConnectEx" which is available via the SDKHooks or the
//       SM core depending on version. In SM 1.11+ it is part of core.
// ─────────────────────────────────────────────────────────────────────────────

public bool OnClientPreConnectEx(const char[] name, char password[255],
    const char[] ip, const char[] steamID, char rejectReason[255])
{
    #pragma unused name, password, ip
    // Always allow bots and LAN clients (steamID will be "BOT" or empty)
    if (StrEqual(steamID, "BOT", false) || steamID[0] == '\0')
        return true;

    // Check if the SteamID is whitelisted
    if (IsWhitelisted(steamID))
        return true;

    // Not on the roster — reject the connection
    Format(rejectReason, sizeof(rejectReason),
        "You are not authorized to join this match. (SteamID: %s)", steamID);
    LogMessage("[MM-Match] Rejected connection from %s (%s) — not on roster.", name, steamID);
    return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerConnectFull — cache SteamID, mark DB row as connected
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerConnectFull(Event event, const char[] name, bool dontBroadcast)
{
    #pragma unused name, dontBroadcast
    int client = GetClientOfUserId(event.GetInt("userid"));
    if (!MM_IsValidClient(client))
        return Plugin_Continue;

    GetClientAuthId(client, AuthId_Steam2, g_sSteamId[client], sizeof(g_sSteamId[]));

    LogMessage("[MM-Match] Player connected: %N (%s)", client, g_sSteamId[client]);

    // Mark connected in DB
    if (g_hDB != null && g_iMatchId > 0)
    {
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_match_players SET connected=1, connected_at=NOW() WHERE match_id=%d AND steam_id='%s'",
            g_iMatchId, g_sSteamId[client]);
        g_hDB.Query(CB_GenericQuery, query);
    }

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerDisconnect — mark abandoned if match is live
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerDisconnect(Event event, const char[] name, bool dontBroadcast)
{
    #pragma unused name, dontBroadcast
    int client = GetClientOfUserId(event.GetInt("userid"));
    if (client <= 0 || IsFakeClient(client))
        return Plugin_Continue;

    // Only flag as abandoned if the match is live/overtime
    if ((g_eMatchState == MatchState_Live || g_eMatchState == MatchState_Overtime)
        && g_hDB != null && g_iMatchId > 0 && g_sSteamId[client][0] != '\0')
    {
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_match_players SET abandoned=1 WHERE match_id=%d AND steam_id='%s'",
            g_iMatchId, g_sSteamId[client]);
        g_hDB.Query(CB_GenericQuery, query);

        MM_PrintToChatAll("\x0C%N has disconnected!", client);
    }

    // Clear cached SteamID
    g_sSteamId[client][0] = '\0';

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Timer_CheckAllConnected — fires every 5 s during warmup
//
// Iterates all whitelisted SteamIDs and checks if they are present in-game.
// Once every expected player is in-game, starts the match.
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_CheckAllConnected(Handle timer)
{
    // If already live, cancel this repeating timer
    if (g_bAllConnected || g_eMatchState != MatchState_Warmup)
    {
        g_hCheckTimer = null;
        return Plugin_Stop;
    }

    int totalExpected = g_iTeam1Count + g_iTeam2Count;
    if (totalExpected == 0)
    {
        // No roster data — can't verify; don't auto-start
        return Plugin_Continue;
    }

    // Count how many whitelisted players are in-game right now
    int connectedCount = 0;
    for (int i = 1; i <= MaxClients; i++)
    {
        if (!MM_IsValidClient(i))
            continue;

        char sid[32];
        GetClientAuthId(i, AuthId_Steam2, sid, sizeof(sid));
        if (IsWhitelisted(sid))
            connectedCount++;
    }

    LogMessage("[MM-Match] Connected check: %d/%d players in-game",
        connectedCount, totalExpected);

    if (connectedCount >= totalExpected)
    {
        // All players present — start knife round
        StartKnifeRound();
        g_hCheckTimer = null;
        return Plugin_Stop;
    }

    // Print status to connected players every check
    MM_PrintToChatAll("Waiting for players... \x04%d/%d\x01 connected.",
        connectedCount, totalExpected);

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// StartKnifeRound — transition from warmup → knife round
// Called once all expected players are connected.
// ─────────────────────────────────────────────────────────────────────────────

void StartKnifeRound()
{
    if (g_eMatchState != MatchState_Warmup)
        return;

    g_bAllConnected = true;
    g_eMatchState   = MatchState_Knife;

    // Cancel warmup timeout — no longer needed
    CancelTimerSafe(g_hWarmupTimer);
    CancelTimerSafe(g_hMapVoteTimer);

    // Reset knife kills for accurate tracking
    for (int i = 0; i <= MAXPLAYERS; i++) g_iKnifeKills[i] = 0;

    ServerCommand("exec knife_round.cfg");
    ServerCommand("mp_warmup_end");
    ServerCommand("mp_restartgame 1");

    MM_PrintToChatAll("\x04All players connected! Knife round starting — winner chooses side.");
    LogMessage("[MM-Match] All players connected — knife round starting.");
}

// ─────────────────────────────────────────────────────────────────────────────
// StartLiveMatch — transition from knife → live
// Called after the knife-round winner has chosen their side.
// ─────────────────────────────────────────────────────────────────────────────

void StartLiveMatch()
{
    g_eMatchState = MatchState_Live;

    ServerCommand("exec gamemode_competitive.cfg");
    ServerCommand("mp_restartgame 3");

    MM_PrintToChatAll("\x04Match is live! Good luck, have fun!");
    LogMessage("[MM-Match] Match going live.");

    // Update DB status to 'live'
    if (g_hDB != null && g_iMatchId > 0)
    {
        char query[256];
        Format(query, sizeof(query),
            "UPDATE mm_matches SET status='live', live_at=NOW() WHERE id=%d",
            g_iMatchId);
        g_hDB.Query(CB_GenericQuery, query);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Timer_WarmupTimeout — fires 180 s after map start
//
// If g_bAllConnected is already true, the match is live and we do nothing.
// Otherwise, cancel the match and redirect connected players to lobby.
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_WarmupTimeout(Handle timer)
{
    g_hWarmupTimer = null;

    if (g_bAllConnected)
    {
        // Match already started — nothing to do
        return Plugin_Stop;
    }

    LogMessage("[MM-Match] Warmup timeout — not all players connected. Cancelling match.");
    MM_PrintToChatAll("\x0CWarmup timed out! Not all players connected. Returning to lobby...");

    // Update DB to cancelled
    if (g_hDB != null && g_iMatchId > 0)
    {
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_matches SET status='cancelled', cancel_reason='Warmup timeout - not all players connected' WHERE id=%d",
            g_iMatchId);
        g_hDB.Query(CB_GenericQuery, query);
    }

    // Redirect all connected players back to lobby after a brief delay
    CreateTimer(5.0, Timer_RedirectToLobby);

    return Plugin_Stop;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerDeath — track kills / deaths / assists / headshots
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerDeath(Event event, const char[] name, bool dontBroadcast)
{
    #pragma unused name, dontBroadcast

    int victim   = GetClientOfUserId(event.GetInt("userid"));
    int attacker = GetClientOfUserId(event.GetInt("attacker"));

    // Track kills during knife round for side-choice captain determination
    if (g_eMatchState == MatchState_Knife)
    {
        if (IsValidClientIndex(attacker) && attacker != victim)
            g_iKnifeKills[attacker]++;
        return Plugin_Continue;
    }

    // Only count stats during live play
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    int assister = GetClientOfUserId(event.GetInt("assister"));
    bool headshot = event.GetBool("headshot");

    if (IsValidClientIndex(victim))
        g_iDeaths[victim]++;

    if (IsValidClientIndex(attacker) && attacker != victim)
    {
        g_iKills[attacker]++;
        if (headshot)
            g_iHeadshots[attacker]++;
    }

    if (IsValidClientIndex(assister))
        g_iAssists[assister]++;

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerHurt — accumulate damage dealt
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerHurt(Event event, const char[] name, bool dontBroadcast)
{
    #pragma unused name, dontBroadcast
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    int attacker   = GetClientOfUserId(event.GetInt("attacker"));
    int dmgDealt   = event.GetInt("dmg_health");

    // attacker == 0 is world damage; skip
    if (IsValidClientIndex(attacker) && dmgDealt > 0)
        g_iDamage[attacker] += dmgDealt;

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerMVP — increment MVP counter
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerMVP(Event event, const char[] name, bool dontBroadcast)
{
    #pragma unused name, dontBroadcast
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    int client = GetClientOfUserId(event.GetInt("userid"));
    if (IsValidClientIndex(client))
        g_iMVPs[client]++;

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_RoundEnd — update per-client score and check for overtime
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_RoundEnd(Event event, const char[] name, bool dontBroadcast)
{
    #pragma unused name, dontBroadcast

    // ── Knife round end: determine winner, offer side choice ──────────
    if (g_eMatchState == MatchState_Knife)
    {
        int winner = event.GetInt("winner");  // CS_TEAM_CT or CS_TEAM_T
        g_iKnifeWinCSTeam = winner;

        char side[4];
        Format(side, sizeof(side), (winner == CS_TEAM_CT) ? "CT" : "T");
        MM_PrintToChatAll("\x04Knife round over! \x09%s\x04 wins — choosing side...", side);
        LogMessage("[MM-Match] Knife round won by CS team %d (%s)", winner, side);

        // Delay the menu by 2 s so the round-end panel fades
        CreateTimer(2.0, Timer_ShowKnifeMenu, _, TIMER_FLAG_NO_MAPCHANGE);
        return Plugin_Continue;
    }

    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    g_iRoundsPlayed++;

    // Snapshot the scoreboard score for each client at round end
    for (int i = 1; i <= MaxClients; i++)
    {
        if (MM_IsValidClient(i))
            g_iScore[i] = GetClientFrags(i);
    }

    // Check if we've entered overtime (scores tied at mp_maxrounds)
    int maxRounds = GetConVarInt(FindConVar("mp_maxrounds"));
    int ctScore   = CS_GetTeamScore(CS_TEAM_CT);
    int tScore    = CS_GetTeamScore(CS_TEAM_T);
    int total     = ctScore + tScore;

    if (total >= maxRounds && ctScore == tScore
        && g_eMatchState == MatchState_Live)
    {
        g_eMatchState = MatchState_Overtime;
        MM_PrintToChatAll("\x09Overtime! Score is tied at %d - %d.", ctScore, tScore);
        LogMessage("[MM-Match] Match entered overtime at %d-%d.", ctScore, tScore);
    }

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_MatchEnd — cs_win_panel_match (PostNoCopy)
//
// Fires once the match is conclusively over. We:
//   1. Determine final scores and winner
//   2. Persist stats to DB
//   3. Print result to all players
//   4. Schedule lobby redirect
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_MatchEnd(Event event, const char[] name, bool dontBroadcast)
{
    #pragma unused name, dontBroadcast
    // Guard: only process once
    if (g_eMatchState == MatchState_Finished)
        return Plugin_Continue;

    g_eMatchState = MatchState_Finished;

    // Cancel warmup-related timers if still running (shouldn't be, but safe)
    CancelTimerSafe(g_hCheckTimer);
    CancelTimerSafe(g_hWarmupTimer);

    // ------------------------------------------------------------------
    // Map CS:GO teams back to our team1/team2 based on starting sides.
    // g_iTeam1CSTeam is either CS_TEAM_CT or CS_TEAM_T.
    // ------------------------------------------------------------------
    int team1Score, team2Score;
    if (g_iTeam1CSTeam == CS_TEAM_CT)
    {
        // This works for both normal and post-halftime because CS:GetTeamScore
        // returns the cumulative score for whichever side CT is now, but
        // the game tracks by team slot (1/2) not by side, so we need
        // to use the correct team index.
        // For correct results we store team scores by CS team number (1/2).
        team1Score = CS_GetTeamScore(CS_TEAM_CT);
        team2Score = CS_GetTeamScore(CS_TEAM_T);
    }
    else
    {
        team1Score = CS_GetTeamScore(CS_TEAM_T);
        team2Score = CS_GetTeamScore(CS_TEAM_CT);
    }

    // Determine winner
    char winner[8];
    if (team1Score > team2Score)
        strcopy(winner, sizeof(winner), "team1");
    else if (team2Score > team1Score)
        strcopy(winner, sizeof(winner), "team2");
    else
        strcopy(winner, sizeof(winner), "tie");

    LogMessage("[MM-Match] Match over! Team1=%d Team2=%d Winner=%s",
        team1Score, team2Score, winner);

    // ------------------------------------------------------------------
    // Announce result to all players
    // ------------------------------------------------------------------
    MM_PrintToChatAll("\x04Match Over! \x01Team1 \x09%d\x01 - \x09%d\x01 Team2",
        team1Score, team2Score);

    if (StrEqual(winner, "tie"))
        MM_PrintToChatAll("\x07The match ended in a draw!");
    else if (StrEqual(winner, "team1"))
        MM_PrintToChatAll("\x04Team 1 wins the match!");
    else
        MM_PrintToChatAll("\x04Team 2 wins the match!");

    // ------------------------------------------------------------------
    // Persist stats and update mm_matches
    // ------------------------------------------------------------------
    if (g_hDB != null && g_iMatchId > 0)
    {
        // Update match record
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_matches SET status='finished', team1_score=%d, team2_score=%d, winner='%s', ended_at=NOW() WHERE id=%d",
            team1Score, team2Score, winner, g_iMatchId);
        g_hDB.Query(CB_GenericQuery, query);

        // Save all player stats (async, threaded)
        SaveAllPlayerStats();
    }

    // ------------------------------------------------------------------
    // Print per-player stats panel to every connected player
    // ------------------------------------------------------------------
    PrintEndOfMatchStats(team1Score, team2Score, winner);

    // ------------------------------------------------------------------
    // Schedule lobby redirect with countdown announcements
    // ------------------------------------------------------------------
    g_iRedirectCountdown = 15;
    CreateTimer(1.0, Timer_CountdownAnnounce, _, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Timer_CountdownAnnounce — 1-second countdown to redirect
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_CountdownAnnounce(Handle timer)
{
    if (g_iRedirectCountdown <= 0)
    {
        // Fire the actual redirect
        CreateTimer(0.1, Timer_RedirectToLobby);
        g_hCountdownTimer = null;
        return Plugin_Stop;
    }

    // Only announce at certain intervals to avoid chat spam
    if (g_iRedirectCountdown <= 5 || g_iRedirectCountdown % 5 == 0)
    {
        MM_PrintToChatAll("\x09Returning to lobby in \x04%d\x09 second%s...",
            g_iRedirectCountdown,
            g_iRedirectCountdown == 1 ? "" : "s");
    }

    g_iRedirectCountdown--;
    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Timer_RedirectToLobby — connect all clients to the lobby server
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_RedirectToLobby(Handle timer)
{
    if (g_sLobbyIP[0] == '\0')
    {
        LogError("[MM-Match] Timer_RedirectToLobby: mm_lobby_ip is empty — cannot redirect.");
        MM_PrintToChatAll("\x0CCould not redirect to lobby (no lobby IP configured).");
        return Plugin_Stop;
    }

    MM_PrintToChatAll("\x04Connecting to lobby server...");
    LogMessage("[MM-Match] Redirecting all players to lobby: %s", g_sLobbyIP);

    for (int i = 1; i <= MaxClients; i++)
    {
        if (MM_IsValidClient(i))
        {
            // "connect IP:PORT" drops the player to the specified server
            ClientCommand(i, "connect %s", g_sLobbyIP);
        }
    }

    return Plugin_Stop;
}

// ─────────────────────────────────────────────────────────────────────────────
// SaveAllPlayerStats — write per-player stats to mm_match_players
//
// Issues one threaded UPDATE per connected player to avoid blocking the
// server thread. Each query is independent so order doesn't matter.
// ─────────────────────────────────────────────────────────────────────────────

void SaveAllPlayerStats()
{
    if (g_hDB == null || g_iMatchId <= 0)
        return;

    for (int i = 1; i <= MaxClients; i++)
    {
        // Save stats for any client with a known SteamID (even disconnected)
        if (g_sSteamId[i][0] == '\0')
            continue;

        // Escape the SteamID to prevent SQL injection (it's user-derived)
        char escapedSID[64];
        g_hDB.Escape(g_sSteamId[i], escapedSID, sizeof(escapedSID));

        char query[768];
        Format(query, sizeof(query),
            "UPDATE mm_match_players SET kills=%d, deaths=%d, assists=%d, headshots=%d, mvps=%d, score=%d, damage=%d WHERE match_id=%d AND steam_id='%s'",
            g_iKills[i], g_iDeaths[i], g_iAssists[i], g_iHeadshots[i],
            g_iMVPs[i], g_iScore[i], g_iDamage[i],
            g_iMatchId, escapedSID);

        g_hDB.Query(CB_SaveStats, query, i);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// sm_score command — display current match score in chat
// ─────────────────────────────────────────────────────────────────────────────

public Action Cmd_Score(int client, int args)
{
    if (!MM_IsValidClient(client))
        return Plugin_Handled;

    int ctScore   = CS_GetTeamScore(CS_TEAM_CT);
    int tScore    = CS_GetTeamScore(CS_TEAM_T);
    int team1Score = (g_iTeam1CSTeam == CS_TEAM_CT) ? ctScore : tScore;
    int team2Score = (g_iTeam1CSTeam == CS_TEAM_CT) ? tScore  : ctScore;

    // Approximate current round number from total rounds played
    int roundNum = ctScore + tScore;

    int maxRounds = GetConVarInt(FindConVar("mp_maxrounds"));
    char stateStr[16];
    switch (g_eMatchState)
    {
        case MatchState_Warmup:   strcopy(stateStr, sizeof(stateStr), "Warmup");
        case MatchState_Knife:    strcopy(stateStr, sizeof(stateStr), "Knife");
        case MatchState_Live:     strcopy(stateStr, sizeof(stateStr), "Live");
        case MatchState_Overtime: strcopy(stateStr, sizeof(stateStr), "Overtime");
        case MatchState_Finished: strcopy(stateStr, sizeof(stateStr), "Finished");
    }

    MM_PrintToChat(client,
        "Score: \x04Team1 %d\x01 - \x04%d Team2\x01 | Round %d/%d | %s",
        team1Score, team2Score, roundNum, maxRounds, stateStr);

    return Plugin_Handled;
}

// ─────────────────────────────────────────────────────────────────────────────
// DB helper: Set mm_matches.status
// ─────────────────────────────────────────────────────────────────────────────

void DB_SetMatchStatus(const char[] status)
{
    if (g_hDB == null || g_iMatchId <= 0)
        return;

    char query[256];
    Format(query, sizeof(query),
        "UPDATE mm_matches SET status='%s' WHERE id=%d",
        status, g_iMatchId);
    g_hDB.Query(CB_GenericQuery, query);
}

// ─────────────────────────────────────────────────────────────────────────────
// DB_QueryTeamSides — determine which CS team (CT/T) team1 started as.
//
// mm_match_players has a `team` column ('team1'/'team2'). We use the match
// record alongside player data to infer starting sides.
//
// Simplified approach: query the first team1 player's CS:GO team assignment
// at match start by checking the `team` column. We store side-assignment
// in the match table via a convention: team1 always starts CT in the DB
// unless the matchmaker specifies otherwise (future enhancement).
//
// For now: default to team1=CT, team2=T, and query DB to confirm.
// ─────────────────────────────────────────────────────────────────────────────

void DB_QueryTeamSides()
{
    if (g_hDB == null || g_iMatchId <= 0)
        return;

    // We default to team1=CT; the query result will override if needed.
    // A future enhancement would store side choice in the match row.
    // For now, the default (team1=CT) is applied; this function is a hook
    // point for that future logic.
    g_iTeam1CSTeam = CS_TEAM_CT;
    g_iTeam2CSTeam = CS_TEAM_T;

    LogMessage("[MM-Match] Team sides: Team1=%s Team2=%s",
        (g_iTeam1CSTeam == CS_TEAM_CT) ? "CT" : "T",
        (g_iTeam2CSTeam == CS_TEAM_CT) ? "CT" : "T");
}

// ─────────────────────────────────────────────────────────────────────────────
// SQL Callbacks
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generic fire-and-forget callback.
 * Logs errors but otherwise ignores results.
 */
public void CB_GenericQuery(Database db, DBResultSet results, const char[] error, any data)
{
    if (db == null || results == null)
        LogError("[MM-Match] DB query error: %s", error);
}

/**
 * Callback for SaveAllPlayerStats() — logs per-player save success/failure.
 * `data` is the client index (1-based).
 */
public void CB_SaveStats(Database db, DBResultSet results, const char[] error, any data)
{
    int client = view_as<int>(data);
    if (db == null || results == null)
    {
        LogError("[MM-Match] Failed to save stats for client %d (%s): %s",
            client, g_sSteamId[client], error);
        return;
    }
    LogMessage("[MM-Match] Stats saved for %s (client %d).", g_sSteamId[client], client);
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper utilities
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Returns true if `steamId` is in the team1 or team2 roster.
 */
bool IsWhitelisted(const char[] steamId)
{
    for (int i = 0; i < g_iTeam1Count; i++)
    {
        if (StrEqual(g_sTeam1SteamIds[i], steamId, false))
            return true;
    }
    for (int i = 0; i < g_iTeam2Count; i++)
    {
        if (StrEqual(g_sTeam2SteamIds[i], steamId, false))
            return true;
    }
    return false;
}

/**
 * Returns true if `client` is a valid, in-bounds client index
 * (does NOT require IsClientInGame — safe to use in pre-connect hooks).
 */
bool IsValidClientIndex(int client)
{
    return (client > 0 && client <= MaxClients);
}

/**
 * Resets all per-client stat arrays to zero and clears SteamID cache.
 */
void ResetAllClientStats()
{
    for (int i = 0; i <= MAXPLAYERS; i++)
    {
        g_iKills[i]      = 0;
        g_iDeaths[i]     = 0;
        g_iAssists[i]    = 0;
        g_iHeadshots[i]  = 0;
        g_iMVPs[i]       = 0;
        g_iDamage[i]     = 0;
        g_iScore[i]      = 0;
        g_sSteamId[i][0] = '\0';
    }
}

/**
 * Safely cancels a timer handle and sets it to null.
 * Avoids double-free errors.
 */
void CancelTimerSafe(Handle &hTimer)
{
    if (hTimer != null)
    {
        KillTimer(hTimer);
        hTimer = null;
    }
}

/**
 * Returns 0 (team1 index) or 1 (team2 index) based on the client's SteamID.
 * Returns -1 if the client is not on a known team.
 */
int GetPlayerTeamIndex(int client)
{
    if (!IsValidClientIndex(client) || g_sSteamId[client][0] == '\0')
        return -1;

    for (int i = 0; i < g_iTeam1Count; i++)
    {
        if (StrEqual(g_sTeam1SteamIds[i], g_sSteamId[client], false))
            return 0;
    }
    for (int i = 0; i < g_iTeam2Count; i++)
    {
        if (StrEqual(g_sTeam2SteamIds[i], g_sSteamId[client], false))
            return 1;
    }
    return -1;
}

// ─────────────────────────────────────────────────────────────────────────────
// MAP VOTE (Phase 5.1)
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_StartMapVote(Handle timer)
{
    if (g_bMapVoteDone || g_hDB == null || g_eMatchState != MatchState_Warmup)
        return Plugin_Stop;

    char query[256];
    Format(query, sizeof(query),
        "SELECT map_name, display_name FROM mm_map_pool WHERE is_active=1 ORDER BY weight DESC LIMIT 5");
    g_hDB.Query(CB_MapVoteList, query);
    return Plugin_Stop;
}

public void CB_MapVoteList(Database db, DBResultSet results, const char[] error, any data)
{
    if (results == null || results.RowCount == 0)
    {
        // No maps in DB — skip vote, keep current map
        g_bMapVoteDone = true;
        LogMessage("[MM-Match] Map vote: no maps in pool, skipping vote.");
        return;
    }

    g_iMapVoteCount = 0;
    while (results.FetchRow() && g_iMapVoteCount < 5)
    {
        results.FetchString(0, g_sMapVoteMaps[g_iMapVoteCount], sizeof(g_sMapVoteMaps[]));
        results.FetchString(1, g_sMapVoteDisplay[g_iMapVoteCount], sizeof(g_sMapVoteDisplay[]));
        g_iMapVotes[g_iMapVoteCount] = 0;
        g_iMapVoteCount++;
    }

    if (g_iMapVoteCount == 0)
    {
        g_bMapVoteDone = true;
        return;
    }

    ShowMapVoteMenuToAll();

    // Vote expires in 20 seconds
    g_hMapVoteTimer = CreateTimer(20.0, Timer_MapVoteExpiry, _, TIMER_FLAG_NO_MAPCHANGE);
    MM_PrintToChatAll("\x09Map vote started! \x04Vote for your map — closes in 20 seconds.");
}

void ShowMapVoteMenuToAll()
{
    for (int i = 1; i <= MaxClients; i++)
    {
        if (MM_IsValidClient(i))
            ShowMapVoteMenuToClient(i);
    }
}

void ShowMapVoteMenuToClient(int client)
{
    Menu menu = new Menu(Menu_MapVoteHandler);
    menu.SetTitle("Vote for Map:");
    menu.ExitButton = false;

    for (int i = 0; i < g_iMapVoteCount; i++)
    {
        char slotStr[4];
        IntToString(i, slotStr, sizeof(slotStr));
        menu.AddItem(slotStr, g_sMapVoteDisplay[i]);
    }

    menu.Display(client, 20);
}

public int Menu_MapVoteHandler(Menu menu, MenuAction action, int client, int param2)
{
    if (action == MenuAction_Select && !g_bMapVoteDone)
    {
        char slotStr[4];
        menu.GetItem(param2, slotStr, sizeof(slotStr));
        int slot = StringToInt(slotStr);
        if (slot >= 0 && slot < g_iMapVoteCount)
        {
            g_iMapVotes[slot]++;
            MM_PrintToChat(client, "You voted for \x04%s\x01.", g_sMapVoteDisplay[slot]);
        }
    }
    else if (action == MenuAction_End)
        delete menu;

    return 0;
}

public Action Timer_MapVoteExpiry(Handle timer)
{
    g_hMapVoteTimer = null;
    if (g_bMapVoteDone) return Plugin_Stop;
    g_bMapVoteDone = true;

    // Find winner (or pick weighted random on tie using weight index as tiebreaker)
    int winSlot = 0;
    for (int i = 1; i < g_iMapVoteCount; i++)
    {
        if (g_iMapVotes[i] > g_iMapVotes[winSlot])
            winSlot = i;
    }

    MM_PrintToChatAll("\x04Map vote over! \x09%s\x04 wins with %d vote(s).",
        g_sMapVoteDisplay[winSlot], g_iMapVotes[winSlot]);

    // Check if the winning map is already loaded
    char currentMap[64];
    GetCurrentMap(currentMap, sizeof(currentMap));
    if (!StrEqual(currentMap, g_sMapVoteMaps[winSlot], false))
    {
        MM_PrintToChatAll("Changing map to \x04%s\x01 in 5 seconds...", g_sMapVoteDisplay[winSlot]);

        // Store winning map name in the match record
        if (g_hDB != null && g_iMatchId > 0)
        {
            char escapedMap[64];
            g_hDB.Escape(g_sMapVoteMaps[winSlot], escapedMap, sizeof(escapedMap));
            char query[256];
            Format(query, sizeof(query),
                "UPDATE mm_matches SET map_name='%s' WHERE id=%d",
                escapedMap, g_iMatchId);
            g_hDB.Query(CB_GenericQuery, query);
        }

        // Stash winning map in slot 0 for use by Timer_DoChangelevel
        strcopy(g_sMapVoteMaps[0], sizeof(g_sMapVoteMaps[]), g_sMapVoteMaps[winSlot]);
        CreateTimer(5.0, Timer_DoChangelevel, _, TIMER_FLAG_NO_MAPCHANGE);
    }

    return Plugin_Stop;
}

public Action Timer_DoChangelevel(Handle timer)
{
    ServerCommand("changelevel %s", g_sMapVoteMaps[0]);
    return Plugin_Stop;
}

// ─────────────────────────────────────────────────────────────────────────────
// KNIFE ROUND (Phase 5.2)
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_ShowKnifeMenu(Handle timer)
{
    if (g_iKnifeWinCSTeam == 0) return Plugin_Stop;

    // Find the captain (is_captain=1) or fallback to most knife kills
    int captain = -1;
    for (int i = 1; i <= MaxClients; i++)
    {
        if (!MM_IsValidClient(i)) continue;
        int cs_team = GetClientTeam(i);
        if (cs_team != g_iKnifeWinCSTeam) continue;

        // Check if this player is the captain (is_captain=1 means highest ELO on their team)
        // We use knife kills as tiebreaker — pick the one with most kills
        if (captain == -1 || g_iKnifeKills[i] > g_iKnifeKills[captain])
            captain = i;
    }

    if (captain == -1)
    {
        // Fallback: no one found — auto-choose, stay as is
        StartLiveMatch();
        return Plugin_Stop;
    }

    Menu menu = new Menu(Menu_KnifeWinnerSideChoice);
    menu.SetTitle("Your team won the knife!\nChoose your starting side:");
    menu.ExitButton = false;
    menu.AddItem("stay",   "Stay CT");
    menu.AddItem("switch", "Switch to T");
    menu.Display(captain, 15);

    MM_PrintToChatAll("\x04%N\x01 is choosing the starting side (15s)...", captain);

    // Auto-choose after 15 s if no answer
    CreateTimer(16.0, Timer_KnifeAutoChoose, GetClientUserId(captain), TIMER_FLAG_NO_MAPCHANGE);

    return Plugin_Stop;
}

public int Menu_KnifeWinnerSideChoice(Menu menu, MenuAction action, int client, int param2)
{
    if (action == MenuAction_Select)
    {
        if (g_eMatchState != MatchState_Knife) { delete menu; return 0; }

        char choice[8];
        menu.GetItem(param2, choice, sizeof(choice));

        if (StrEqual(choice, "switch"))
        {
            // Swap teams
            ServerCommand("mp_swapteams");
            MM_PrintToChatAll("\x04%N chose to \x09Switch to T\x04 — teams swapped!", client);
        }
        else
        {
            MM_PrintToChatAll("\x04%N chose to \x09Stay CT\x04.", client);
        }

        StartLiveMatch();
    }
    else if (action == MenuAction_End)
        delete menu;

    return 0;
}

public Action Timer_KnifeAutoChoose(Handle timer, any userId)
{
    if (g_eMatchState != MatchState_Knife) return Plugin_Stop;

    int client = GetClientOfUserId(userId);
    if (client > 0)
        MM_PrintToChatAll("\x0CSide choice timed out — \x04staying CT\x0C.", client);
    else
        MM_PrintToChatAll("\x0CSide choice timed out — staying CT.");

    StartLiveMatch();
    return Plugin_Stop;
}

// ─────────────────────────────────────────────────────────────────────────────
// END-OF-MATCH STATS PANEL (Phase 5.3)
// ─────────────────────────────────────────────────────────────────────────────

void PrintEndOfMatchStats(int team1Score, int team2Score, const char[] winner)
{

    for (int i = 1; i <= MaxClients; i++)
    {
        if (!MM_IsValidClient(i) || g_sSteamId[i][0] == '\0') continue;

        int teamIdx = GetPlayerTeamIndex(i);
        char myResult[8];

        if (StrEqual(winner, "tie"))
            strcopy(myResult, sizeof(myResult), "Draw");
        else if ((StrEqual(winner, "team1") && teamIdx == 0) ||
                 (StrEqual(winner, "team2") && teamIdx == 1))
            strcopy(myResult, sizeof(myResult), "Win");
        else
            strcopy(myResult, sizeof(myResult), "Loss");

        int hs_pct = (g_iKills[i] > 0) ? RoundToNearest(float(g_iHeadshots[i]) * 100.0 / float(g_iKills[i])) : 0;

        MM_PrintToChat(i, "\x09\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550");
        MM_PrintToChat(i, "\x04[MM] Match over \x01— %d - %d (\x04%s\x01)",
            team1Score, team2Score, myResult);
        MM_PrintToChat(i, "\x04[MM] Stats: \x01%dK / %dD / %dA | %d%% HS | %d dmg",
            g_iKills[i], g_iDeaths[i], g_iAssists[i], hs_pct, g_iDamage[i]);
        MM_PrintToChat(i, "\x04[MM] \x01Rating update coming shortly — check \x04!lastmatch\x01 on the lobby.");
        MM_PrintToChat(i, "\x09\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550");
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// TACTICAL PAUSE (Phase 5.4)
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_FreezeEnd(Event event, const char[] name, bool dontBroadcast)
{
    #pragma unused name, dontBroadcast
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    // Check if either team requested a pause
    for (int t = 0; t < 2; t++)
    {
        if (g_bPauseRequested[t] && g_iPausesLeft[t] > 0)
        {
            g_bPauseRequested[t] = false;
            g_bUnpauseReady[0]   = false;
            g_bUnpauseReady[1]   = false;
            g_bPaused            = true;
            g_iPausesLeft[t]--;

            ServerCommand("mp_pause_match");
            MM_PrintToChatAll("\x09[MM] Team %d called a tactical timeout. (%d remaining) Type \x04!unpause\x09 when ready.",
                t + 1, g_iPausesLeft[t]);

            // Auto-unpause after 60 seconds
            g_hPauseTimer = CreateTimer(60.0, Timer_AutoUnpause, _, TIMER_FLAG_NO_MAPCHANGE);
            break;
        }
    }

    return Plugin_Continue;
}

public Action Cmd_Pause(int client, int args)
{
    if (!MM_IsValidClient(client)) return Plugin_Handled;
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
    {
        MM_PrintToChat(client, "[MM] Tactical timeout is only available during live play.");
        return Plugin_Handled;
    }

    int teamIdx = GetPlayerTeamIndex(client);
    if (teamIdx < 0)
    {
        MM_PrintToChat(client, "[MM] You are not on a registered team.");
        return Plugin_Handled;
    }

    if (g_bPaused)
    {
        MM_PrintToChat(client, "[MM] Match is already paused. Type \x04!unpause\x01 when ready.");
        return Plugin_Handled;
    }

    if (g_iPausesLeft[teamIdx] <= 0)
    {
        MM_PrintToChat(client, "[MM] Your team has no tactical timeouts remaining.");
        return Plugin_Handled;
    }

    if (g_bPauseRequested[teamIdx])
    {
        MM_PrintToChat(client, "[MM] Pause already requested for your team — takes effect at next freeze time.");
        return Plugin_Handled;
    }

    g_bPauseRequested[teamIdx] = true;
    MM_PrintToChatAll("\x09[MM] Team %d requested a tactical timeout — takes effect at next freeze time.",
        teamIdx + 1);

    return Plugin_Handled;
}

public Action Cmd_Unpause(int client, int args)
{
    if (!MM_IsValidClient(client)) return Plugin_Handled;

    if (!g_bPaused)
    {
        MM_PrintToChat(client, "[MM] Match is not paused.");
        return Plugin_Handled;
    }

    int teamIdx = GetPlayerTeamIndex(client);
    if (teamIdx < 0) return Plugin_Handled;

    g_bUnpauseReady[teamIdx] = true;
    MM_PrintToChatAll("\x04[MM] Team %d is ready to resume.", teamIdx + 1);

    if (g_bUnpauseReady[0] && g_bUnpauseReady[1])
    {
        CancelTimerSafe(g_hPauseTimer);
        g_bPaused          = false;
        g_bUnpauseReady[0] = false;
        g_bUnpauseReady[1] = false;
        ServerCommand("mp_unpause_match");
        MM_PrintToChatAll("\x04[MM] Match resumed!");
    }
    else
    {
        int otherTeam = (teamIdx == 0) ? 1 : 0;
        if (!g_bUnpauseReady[otherTeam])
            MM_PrintToChatAll("\x09[MM] Waiting for Team %d to type \x04!unpause\x09...", otherTeam + 1);
    }

    return Plugin_Handled;
}

public Action Timer_AutoUnpause(Handle timer)
{
    g_hPauseTimer = null;
    if (!g_bPaused) return Plugin_Stop;

    g_bPaused          = false;
    g_bUnpauseReady[0] = false;
    g_bUnpauseReady[1] = false;
    ServerCommand("mp_unpause_match");
    MM_PrintToChatAll("\x04[MM] Tactical timeout expired — match resumed automatically.");
    return Plugin_Stop;
}

// ─────────────────────────────────────────────────────────────────────────────
// SURRENDER VOTE (Phase 4.1)
// ─────────────────────────────────────────────────────────────────────────────

public Action Cmd_Surrender(int client, int args)
{
    if (!MM_IsValidClient(client)) return Plugin_Handled;
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
    {
        MM_PrintToChat(client, "[MM] Surrender vote is only available during live play.");
        return Plugin_Handled;
    }

    if (g_iRoundsPlayed < 3)
    {
        MM_PrintToChat(client, "[MM] Surrender is only available after 3 rounds have been played.");
        return Plugin_Handled;
    }

    int teamIdx = GetPlayerTeamIndex(client);
    if (teamIdx < 0)
    {
        MM_PrintToChat(client, "[MM] You are not on a registered team.");
        return Plugin_Handled;
    }

    if (g_bSurrenderVote[teamIdx])
    {
        // Vote in progress — cast a yes vote
        g_iSurrenderYes[teamIdx]++;

        // Count team size for threshold
        int teamSize = (teamIdx == 0) ? g_iTeam1Count : g_iTeam2Count;
        int needed   = (teamSize >= 5) ? 4 : (teamSize - 1);

        MM_PrintToChatAll("\x09[MM] Surrender vote: \x04%d/%d\x09 yes votes (need %d).",
            g_iSurrenderYes[teamIdx], teamSize, needed);

        if (g_iSurrenderYes[teamIdx] >= needed)
        {
            CancelTimerSafe(g_hSurrenderTimer[teamIdx]);
            g_bSurrenderVote[teamIdx] = false;
            ExecuteSurrender(teamIdx);
        }
        return Plugin_Handled;
    }

    // Cooldown check
    if (GetGameTime() < g_fSurrenderCooldown[teamIdx])
    {
        MM_PrintToChat(client, "[MM] Your team must wait before calling another surrender vote.");
        return Plugin_Handled;
    }

    // Start new vote
    g_bSurrenderVote[teamIdx]  = true;
    g_iSurrenderYes[teamIdx]   = 1;  // Initiator counts as a yes
    int teamSize = (teamIdx == 0) ? g_iTeam1Count : g_iTeam2Count;
    int needed   = (teamSize >= 5) ? 4 : (teamSize - 1);

    MM_PrintToChatAll("\x09[MM] \x04%N\x09 called a surrender vote for Team %d. (%d/%d needed — type \x04!ff\x09 to vote yes)",
        client, teamIdx + 1, g_iSurrenderYes[teamIdx], needed);

    // Expire in 30 seconds
    DataPack pack = new DataPack();
    pack.WriteCell(teamIdx);
    g_hSurrenderTimer[teamIdx] = CreateTimer(30.0, Timer_SurrenderExpiry, pack, TIMER_FLAG_NO_MAPCHANGE | TIMER_DATA_HNDL_CLOSE);

    return Plugin_Handled;
}

public Action Timer_SurrenderExpiry(Handle timer, DataPack pack)
{
    pack.Reset();
    int teamIdx = pack.ReadCell();
    g_hSurrenderTimer[teamIdx] = null;

    if (!g_bSurrenderVote[teamIdx]) return Plugin_Stop;

    g_bSurrenderVote[teamIdx]    = false;
    g_iSurrenderYes[teamIdx]     = 0;
    g_fSurrenderCooldown[teamIdx] = GetGameTime() + 120.0;

    MM_PrintToChatAll("\x0C[MM] Surrender vote for Team %d failed — not enough yes votes.", teamIdx + 1);
    return Plugin_Stop;
}

void ExecuteSurrender(int surrenderTeamIdx)
{
    // surrenderTeamIdx: 0 = team1 surrenders → team2 wins
    if (g_eMatchState == MatchState_Finished) return;
    g_eMatchState = MatchState_Finished;

    CancelTimerSafe(g_hCheckTimer);
    CancelTimerSafe(g_hWarmupTimer);

    char winner[8];
    Format(winner, sizeof(winner), (surrenderTeamIdx == 0) ? "team2" : "team1");

    int ctScore = CS_GetTeamScore(CS_TEAM_CT);
    int tScore  = CS_GetTeamScore(CS_TEAM_T);
    int team1Score = (g_iTeam1CSTeam == CS_TEAM_CT) ? ctScore : tScore;
    int team2Score = (g_iTeam1CSTeam == CS_TEAM_CT) ? tScore  : ctScore;

    MM_PrintToChatAll("\x0C[MM] Team %d has surrendered! Team %d wins!",
        surrenderTeamIdx + 1, (surrenderTeamIdx == 0) ? 2 : 1);

    if (g_hDB != null && g_iMatchId > 0)
    {
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_matches SET status='finished', team1_score=%d, team2_score=%d, winner='%s', surrendered=1, ended_at=NOW() WHERE id=%d",
            team1Score, team2Score, winner, g_iMatchId);
        g_hDB.Query(CB_GenericQuery, query);

        SaveAllPlayerStats();
    }

    PrintEndOfMatchStats(team1Score, team2Score, winner);

    g_iRedirectCountdown = 15;
    CreateTimer(1.0, Timer_CountdownAnnounce, _, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);
}

// ─────────────────────────────────────────────────────────────────────────────
// REPORT SYSTEM (Phase 4.3)
// ─────────────────────────────────────────────────────────────────────────────

// Per-client: the target SteamID chosen when !report <name> was typed
char g_sReportTarget[MAXPLAYERS+1][32];

public Action Cmd_Report(int client, int args)
{
    if (!MM_IsValidClient(client)) return Plugin_Handled;
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
    {
        MM_PrintToChat(client, "[MM] Reports can only be submitted during a live match.");
        return Plugin_Handled;
    }

    if (args < 1)
    {
        MM_PrintToChat(client, "[MM] Usage: !report <player name>");
        return Plugin_Handled;
    }

    char partialName[MAX_NAME_LENGTH];
    GetCmdArgString(partialName, sizeof(partialName));

    // Find target among in-game clients
    int target = -1;
    for (int i = 1; i <= MaxClients; i++)
    {
        if (i == client || !MM_IsValidClient(i)) continue;
        char playerName[MAX_NAME_LENGTH];
        GetClientName(i, playerName, sizeof(playerName));
        if (StrContains(playerName, partialName, false) != -1)
        {
            target = i;
            break;
        }
    }

    if (target == -1)
    {
        MM_PrintToChat(client, "[MM] Player '%s' not found.", partialName);
        return Plugin_Handled;
    }

    if (g_sSteamId[target][0] == '\0')
    {
        MM_PrintToChat(client, "[MM] Could not retrieve that player's Steam ID.");
        return Plugin_Handled;
    }

    strcopy(g_sReportTarget[client], sizeof(g_sReportTarget[]), g_sSteamId[target]);

    Menu menu = new Menu(Menu_ReportReasonHandler);
    char title[128];
    Format(title, sizeof(title), "Report %N for:", target);
    menu.SetTitle(title);
    menu.ExitButton = true;
    menu.AddItem("cheating",  "Cheating");
    menu.AddItem("griefing",  "Griefing");
    menu.AddItem("afk",       "AFK");
    menu.AddItem("toxic",     "Toxic behavior");
    menu.Display(client, 20);

    return Plugin_Handled;
}

public int Menu_ReportReasonHandler(Menu menu, MenuAction action, int client, int param2)
{
    if (action == MenuAction_Select)
    {
        if (g_hDB == null || g_iMatchId <= 0 || g_sReportTarget[client][0] == '\0')
        {
            MM_PrintToChat(client, "[MM] Could not submit report — database unavailable.");
        }
        else
        {
            char reason[16];
            menu.GetItem(param2, reason, sizeof(reason));

            char escReporter[64], escReported[64], escReason[32];
            g_hDB.Escape(g_sSteamId[client], escReporter, sizeof(escReporter));
            g_hDB.Escape(g_sReportTarget[client], escReported, sizeof(escReported));
            g_hDB.Escape(reason, escReason, sizeof(escReason));

            char query[512];
            Format(query, sizeof(query),
                "INSERT IGNORE INTO mm_reports (reporter_id, reported_id, match_id, reason) "
                "VALUES ('%s', '%s', %d, '%s')",
                escReporter, escReported, g_iMatchId, escReason);
            g_hDB.Query(CB_GenericQuery, query);

            MM_PrintToChat(client, "\x04[MM] Report submitted. Thank you.");
        }

        g_sReportTarget[client][0] = '\0';
    }
    else if (action == MenuAction_End)
        delete menu;

    return 0;
}
