/**
 * csgo_mm_match.sp — CS:GO Matchmaking: Match Lifecycle Plugin
 *
 * Handles the full lifecycle of a competitive 5v5 match:
 *   • Player whitelist enforcement (SteamID-based)
 *   • Warmup phase with all-connected detection
 *   • Live-play stat tracking (kills/deaths/assists/headshots/damage/MVPs)
 *   • Match-end detection via cs_win_panel_match
 *   • Stats persisted to mm_match_players via threaded SQL
 *   • mm_matches status and score updated throughout
 *   • Post-match redirect to lobby server
 *
 * Depends on: csgo_mm.inc, dbi.mysql (SourceMod MySQL extension)
 *
 * ConVars (set via cfg/mm_match.cfg, generated by entrypoint.sh):
 *   mm_match_token  — match token string (also the server password source)
 *   mm_match_id     — integer match ID in mm_matches
 *   mm_lobby_ip     — "IP:PORT" of the lobby server for post-match redirect
 */

#include <sourcemod>
#include <sdktools>
#include <cstrike>
#include <dbi>
#include <csgo_mm>

#pragma semicolon 1
#pragma newdecls required

// ─────────────────────────────────────────────────────────────────────────────
// Plugin metadata
// ─────────────────────────────────────────────────────────────────────────────

public Plugin myinfo = {
    name        = "CS:GO MM — Match Lifecycle",
    author      = "CSGO-Matchmaking Community",
    description = "Manages a single competitive match: whitelist, stats, DB writes, redirect.",
    version     = MM_VERSION,
    url         = ""
};

// ─────────────────────────────────────────────────────────────────────────────
// Global state
// ─────────────────────────────────────────────────────────────────────────────

Database g_hDB = null;

// ConVar handles — values set by cfg/mm_match.cfg before plugin load
ConVar g_cvMatchToken;
ConVar g_cvMatchId;
ConVar g_cvLobbyIP;

// Cached plain values read from ConVars on plugin start
char g_sMatchToken[65];
int  g_iMatchId;
char g_sLobbyIP[64];

// ─────────────────────────────────────────────────────────────────────────────
// Team rosters — populated from env vars via ReadTeamRostersFromEnv()
// ─────────────────────────────────────────────────────────────────────────────

// Maximum 5 per team; SteamIDs are "STEAM_X:Y:Z" (≤ 31 chars + NUL)
char g_sTeam1SteamIds[5][32];
char g_sTeam2SteamIds[5][32];
int  g_iTeam1Count = 0;
int  g_iTeam2Count = 0;

// ─────────────────────────────────────────────────────────────────────────────
// Per-client stats — reset on plugin start / map change
// ─────────────────────────────────────────────────────────────────────────────

int  g_iKills[MAXPLAYERS+1];
int  g_iDeaths[MAXPLAYERS+1];
int  g_iAssists[MAXPLAYERS+1];
int  g_iHeadshots[MAXPLAYERS+1];
int  g_iMVPs[MAXPLAYERS+1];
int  g_iDamage[MAXPLAYERS+1];
int  g_iScore[MAXPLAYERS+1];
char g_sSteamId[MAXPLAYERS+1][32];

// ─────────────────────────────────────────────────────────────────────────────
// Match state machine
// ─────────────────────────────────────────────────────────────────────────────

enum MatchState {
    MatchState_Warmup,
    MatchState_Live,
    MatchState_Overtime,
    MatchState_Finished
}
MatchState g_eMatchState = MatchState_Warmup;

// Set to true once all whitelisted players have connected and gone in-game.
// Prevents the warmup-timeout from cancelling an already-live match.
bool g_bAllConnected = false;

// CS_TEAM_CT / CS_TEAM_T assignment for team1 and team2.
// Populated by querying mm_match_players on OnMapStart (or when DB is ready).
// Default: team1 starts CT (most common; overwritten if DB says otherwise).
int g_iTeam1CSTeam = CS_TEAM_CT;   // CS:GO team constant for team1
int g_iTeam2CSTeam = CS_TEAM_T;    // CS:GO team constant for team2

// Timer handles — kept so we can cancel them when they become irrelevant
Handle g_hCheckTimer    = null;
Handle g_hWarmupTimer   = null;
Handle g_hCountdownTimer = null;

// Redirect countdown seconds remaining
int g_iRedirectCountdown = 15;

// ─────────────────────────────────────────────────────────────────────────────
// OnPluginStart — entry point
// ─────────────────────────────────────────────────────────────────────────────

public void OnPluginStart()
{
    // ------------------------------------------------------------------
    // Register ConVars that cfg/mm_match.cfg will set at map start.
    // We create them first so they exist before the cfg is exec'd.
    // ------------------------------------------------------------------
    g_cvMatchToken = CreateConVar("mm_match_token", "",  "Match token (set by entrypoint)", FCVAR_PROTECTED);
    g_cvMatchId    = CreateConVar("mm_match_id",    "0", "Match ID integer (set by entrypoint)", FCVAR_PROTECTED);
    g_cvLobbyIP    = CreateConVar("mm_lobby_ip",    "",  "Lobby server IP:PORT for post-match redirect", FCVAR_PROTECTED);

    // AutoExecConfig is NOT used here — mm_match.cfg is exec'd by server.cfg
    // which fires before this plugin's ConVars are read below.

    // ------------------------------------------------------------------
    // Hook game events
    // ------------------------------------------------------------------
    HookEvent("player_death",          Event_PlayerDeath);
    HookEvent("player_hurt",           Event_PlayerHurt);
    HookEvent("player_mvp",            Event_PlayerMVP);
    HookEvent("round_end",             Event_RoundEnd);
    HookEvent("cs_win_panel_match",    Event_MatchEnd,   EventHookMode_PostNoCopy);
    HookEvent("player_connect_full",   Event_PlayerConnectFull);
    HookEvent("player_disconnect",     Event_PlayerDisconnect, EventHookMode_Pre);

    // ------------------------------------------------------------------
    // Register chat commands
    // ------------------------------------------------------------------
    RegConsoleCmd("sm_score", Cmd_Score, "Show current match score");

    // ------------------------------------------------------------------
    // Connect to database (async — callback fires when ready)
    // ------------------------------------------------------------------
    Database.Connect(DB_Connected, MM_DB_NAME);

    // ------------------------------------------------------------------
    // Parse team rosters from environment variables.
    // This runs immediately so the whitelist is available even before
    // the DB connection is established.
    // ------------------------------------------------------------------
    ReadTeamRostersFromEnv();

    LogMessage("[MM-Match] Plugin started. Match ID from env (pre-cfg): pending ConVar load.");
}

// ─────────────────────────────────────────────────────────────────────────────
// OnMapStart — fires after server.cfg (and thus mm_match.cfg) has been exec'd.
// This is the reliable point to read ConVar values.
// ─────────────────────────────────────────────────────────────────────────────

public void OnMapStart()
{
    // Read ConVar values now that cfg files have been executed
    g_cvMatchToken.GetString(g_sMatchToken, sizeof(g_sMatchToken));
    g_iMatchId = g_cvMatchId.IntValue;
    g_cvLobbyIP.GetString(g_sLobbyIP, sizeof(g_sLobbyIP));

    LogMessage("[MM-Match] OnMapStart — MatchID=%d  Token=%s  Lobby=%s",
        g_iMatchId, g_sMatchToken, g_sLobbyIP);

    // Reset per-client arrays for fresh map
    ResetAllClientStats();

    // Reset match state
    g_eMatchState    = MatchState_Warmup;
    g_bAllConnected  = false;

    // Cancel any leftover timers from a previous round
    CancelTimerSafe(g_hCheckTimer);
    CancelTimerSafe(g_hWarmupTimer);
    CancelTimerSafe(g_hCountdownTimer);

    // Load warmup config immediately
    ServerCommand("exec warmup.cfg");

    // Periodic timer: fires every 5 s to check whether all players are in
    g_hCheckTimer  = CreateTimer(5.0,   Timer_CheckAllConnected, _, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);

    // Warmup timeout: if not all connected within 3 minutes, cancel match
    g_hWarmupTimer = CreateTimer(180.0, Timer_WarmupTimeout,     _, TIMER_FLAG_NO_MAPCHANGE);

    // If DB already connected, update match status to warmup and query sides
    if (g_hDB != null && g_iMatchId > 0)
    {
        DB_SetMatchStatus(MATCH_STATUS_WARMUP);
        DB_QueryTeamSides();
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// DB_Connected — async callback for Database.Connect()
// ─────────────────────────────────────────────────────────────────────────────

public void DB_Connected(Database db, const char[] error, any data)
{
    if (db == null)
    {
        LogError("[MM-Match] Database connection failed: %s", error);
        // Non-fatal for the server process; stats simply won't be saved.
        // We still allow the match to proceed.
        return;
    }

    g_hDB = db;
    LogMessage("[MM-Match] Database connected successfully.");

    // If OnMapStart has already run and we have a match ID, set warmup status
    if (g_iMatchId > 0)
    {
        DB_SetMatchStatus(MATCH_STATUS_WARMUP);
        DB_QueryTeamSides();
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ReadTeamRostersFromEnv — parse MM_TEAM1_STEAMIDS / MM_TEAM2_STEAMIDS
//
// The env vars are comma-separated SteamIDs: "STEAM_1:0:123,STEAM_1:1:456"
// We split and store them in g_sTeam1SteamIds / g_sTeam2SteamIds.
// ─────────────────────────────────────────────────────────────────────────────

void ReadTeamRostersFromEnv()
{
    char envBuf[512];

    // Team 1
    g_iTeam1Count = 0;
    GetEnvVarString("MM_TEAM1_STEAMIDS", envBuf, sizeof(envBuf));
    if (envBuf[0] != '\0')
    {
        char parts[5][32];
        int count = ExplodeString(envBuf, ",", parts, sizeof(parts), sizeof(parts[]));
        g_iTeam1Count = count;
        for (int i = 0; i < count; i++)
        {
            TrimString(parts[i]);
            strcopy(g_sTeam1SteamIds[i], sizeof(g_sTeam1SteamIds[]), parts[i]);
        }
    }

    // Team 2
    g_iTeam2Count = 0;
    GetEnvVarString("MM_TEAM2_STEAMIDS", envBuf, sizeof(envBuf));
    if (envBuf[0] != '\0')
    {
        char parts[5][32];
        int count = ExplodeString(envBuf, ",", parts, sizeof(parts), sizeof(parts[]));
        g_iTeam2Count = count;
        for (int i = 0; i < count; i++)
        {
            TrimString(parts[i]);
            strcopy(g_sTeam2SteamIds[i], sizeof(g_sTeam2SteamIds[]), parts[i]);
        }
    }

    LogMessage("[MM-Match] Team rosters loaded — Team1: %d players, Team2: %d players",
        g_iTeam1Count, g_iTeam2Count);
}

// ─────────────────────────────────────────────────────────────────────────────
// OnClientPreConnectEx — whitelist gate
//
// Called before the client fully connects. If the SteamID is not on either
// team roster, the connection is rejected with a human-readable message.
//
// NOTE: This forward requires the "Client Preferences" or the standard SM
//       "OnClientPreConnectEx" which is available via the SDKHooks or the
//       SM core depending on version. In SM 1.11+ it is part of core.
// ─────────────────────────────────────────────────────────────────────────────

public bool OnClientPreConnectEx(const char[] name, char password[255],
    const char[] ip, const char[] steamID, char rejectReason[255])
{
    // Always allow bots and LAN clients (steamID will be "BOT" or empty)
    if (StrEqual(steamID, "BOT", false) || steamID[0] == '\0')
        return true;

    // Check if the SteamID is whitelisted
    if (IsWhitelisted(steamID))
        return true;

    // Not on the roster — reject the connection
    Format(rejectReason, sizeof(rejectReason),
        "You are not authorized to join this match. (SteamID: %s)", steamID);
    LogMessage("[MM-Match] Rejected connection from %s (%s) — not on roster.", name, steamID);
    return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerConnectFull — cache SteamID, mark DB row as connected
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerConnectFull(Event event, const char[] name, bool dontBroadcast)
{
    int client = GetClientOfUserId(event.GetInt("userid"));
    if (!MM_IsValidClient(client))
        return Plugin_Continue;

    GetClientAuthId(client, AuthId_Steam2, g_sSteamId[client], sizeof(g_sSteamId[]));

    LogMessage("[MM-Match] Player connected: %N (%s)", client, g_sSteamId[client]);

    // Mark connected in DB
    if (g_hDB != null && g_iMatchId > 0)
    {
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_match_players SET connected=1, connected_at=NOW() WHERE match_id=%d AND steam_id='%s'",
            g_iMatchId, g_sSteamId[client]);
        g_hDB.Query(CB_GenericQuery, query);
    }

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerDisconnect — mark abandoned if match is live
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerDisconnect(Event event, const char[] name, bool dontBroadcast)
{
    int client = GetClientOfUserId(event.GetInt("userid"));
    if (client <= 0 || IsFakeClient(client))
        return Plugin_Continue;

    // Only flag as abandoned if the match is live/overtime
    if ((g_eMatchState == MatchState_Live || g_eMatchState == MatchState_Overtime)
        && g_hDB != null && g_iMatchId > 0 && g_sSteamId[client][0] != '\0')
    {
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_match_players SET abandoned=1 WHERE match_id=%d AND steam_id='%s'",
            g_iMatchId, g_sSteamId[client]);
        g_hDB.Query(CB_GenericQuery, query);

        MM_PrintToChatAll("\x0C%N has disconnected!", client);
    }

    // Clear cached SteamID
    g_sSteamId[client][0] = '\0';

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Timer_CheckAllConnected — fires every 5 s during warmup
//
// Iterates all whitelisted SteamIDs and checks if they are present in-game.
// Once every expected player is in-game, starts the match.
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_CheckAllConnected(Handle timer)
{
    // If already live, cancel this repeating timer
    if (g_bAllConnected || g_eMatchState != MatchState_Warmup)
    {
        g_hCheckTimer = null;
        return Plugin_Stop;
    }

    int totalExpected = g_iTeam1Count + g_iTeam2Count;
    if (totalExpected == 0)
    {
        // No roster data — can't verify; don't auto-start
        return Plugin_Continue;
    }

    // Count how many whitelisted players are in-game right now
    int connectedCount = 0;
    for (int i = 1; i <= MaxClients; i++)
    {
        if (!MM_IsValidClient(i))
            continue;

        char sid[32];
        GetClientAuthId(i, AuthId_Steam2, sid, sizeof(sid));
        if (IsWhitelisted(sid))
            connectedCount++;
    }

    LogMessage("[MM-Match] Connected check: %d/%d players in-game",
        connectedCount, totalExpected);

    if (connectedCount >= totalExpected)
    {
        // All players present — go live
        StartMatch();
        g_hCheckTimer = null;
        return Plugin_Stop;
    }

    // Print status to connected players every check
    MM_PrintToChatAll("Waiting for players... \x04%d/%d\x01 connected.",
        connectedCount, totalExpected);

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// StartMatch — transition from warmup to live
// ─────────────────────────────────────────────────────────────────────────────

void StartMatch()
{
    if (g_eMatchState != MatchState_Warmup)
        return;

    g_bAllConnected = true;
    g_eMatchState   = MatchState_Live;

    // Cancel warmup timeout — no longer needed
    CancelTimerSafe(g_hWarmupTimer);

    // Load competitive config (disables warmup, sets proper round timers)
    ServerCommand("exec gamemode_competitive.cfg");
    ServerCommand("mp_warmup_end");
    ServerCommand("mp_restartgame 1");

    MM_PrintToChatAll("\x04All players connected! Match is starting...");
    LogMessage("[MM-Match] All players connected — match going live.");

    // Update DB status to 'live'
    if (g_hDB != null && g_iMatchId > 0)
    {
        char query[256];
        Format(query, sizeof(query),
            "UPDATE mm_matches SET status='live', live_at=NOW() WHERE id=%d",
            g_iMatchId);
        g_hDB.Query(CB_GenericQuery, query);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Timer_WarmupTimeout — fires 180 s after map start
//
// If g_bAllConnected is already true, the match is live and we do nothing.
// Otherwise, cancel the match and redirect connected players to lobby.
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_WarmupTimeout(Handle timer)
{
    g_hWarmupTimer = null;

    if (g_bAllConnected)
    {
        // Match already started — nothing to do
        return Plugin_Stop;
    }

    LogMessage("[MM-Match] Warmup timeout — not all players connected. Cancelling match.");
    MM_PrintToChatAll("\x0CWarmup timed out! Not all players connected. Returning to lobby...");

    // Update DB to cancelled
    if (g_hDB != null && g_iMatchId > 0)
    {
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_matches SET status='cancelled', cancel_reason='Warmup timeout - not all players connected' WHERE id=%d",
            g_iMatchId);
        g_hDB.Query(CB_GenericQuery, query);
    }

    // Redirect all connected players back to lobby after a brief delay
    CreateTimer(5.0, Timer_RedirectToLobby);

    return Plugin_Stop;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerDeath — track kills / deaths / assists / headshots
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerDeath(Event event, const char[] name, bool dontBroadcast)
{
    // Only count stats during live play
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    int victim   = GetClientOfUserId(event.GetInt("userid"));
    int attacker = GetClientOfUserId(event.GetInt("attacker"));
    int assister = GetClientOfUserId(event.GetInt("assister"));
    bool headshot = event.GetBool("headshot");

    if (IsValidClientIndex(victim))
        g_iDeaths[victim]++;

    if (IsValidClientIndex(attacker) && attacker != victim)
    {
        g_iKills[attacker]++;
        if (headshot)
            g_iHeadshots[attacker]++;
    }

    if (IsValidClientIndex(assister))
        g_iAssists[assister]++;

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerHurt — accumulate damage dealt
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerHurt(Event event, const char[] name, bool dontBroadcast)
{
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    int attacker   = GetClientOfUserId(event.GetInt("attacker"));
    int dmgDealt   = event.GetInt("dmg_health");

    // attacker == 0 is world damage; skip
    if (IsValidClientIndex(attacker) && dmgDealt > 0)
        g_iDamage[attacker] += dmgDealt;

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_PlayerMVP — increment MVP counter
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_PlayerMVP(Event event, const char[] name, bool dontBroadcast)
{
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    int client = GetClientOfUserId(event.GetInt("userid"));
    if (IsValidClientIndex(client))
        g_iMVPs[client]++;

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_RoundEnd — update per-client score and check for overtime
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_RoundEnd(Event event, const char[] name, bool dontBroadcast)
{
    if (g_eMatchState != MatchState_Live && g_eMatchState != MatchState_Overtime)
        return Plugin_Continue;

    // Snapshot the scoreboard score for each client at round end
    for (int i = 1; i <= MaxClients; i++)
    {
        if (MM_IsValidClient(i))
            g_iScore[i] = GetClientFrags(i);
    }

    // Check if we've entered overtime (scores tied at mp_maxrounds)
    int maxRounds = GetConVarInt(FindConVar("mp_maxrounds"));
    int ctScore   = CS_GetTeamScore(CS_TEAM_CT);
    int tScore    = CS_GetTeamScore(CS_TEAM_T);
    int total     = ctScore + tScore;

    if (total >= maxRounds && ctScore == tScore
        && g_eMatchState == MatchState_Live)
    {
        g_eMatchState = MatchState_Overtime;
        MM_PrintToChatAll("\x09Overtime! Score is tied at %d - %d.", ctScore, tScore);
        LogMessage("[MM-Match] Match entered overtime at %d-%d.", ctScore, tScore);
    }

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event_MatchEnd — cs_win_panel_match (PostNoCopy)
//
// Fires once the match is conclusively over. We:
//   1. Determine final scores and winner
//   2. Persist stats to DB
//   3. Print result to all players
//   4. Schedule lobby redirect
// ─────────────────────────────────────────────────────────────────────────────

public Action Event_MatchEnd(Event event, const char[] name, bool dontBroadcast)
{
    // Guard: only process once
    if (g_eMatchState == MatchState_Finished)
        return Plugin_Continue;

    g_eMatchState = MatchState_Finished;

    // Cancel warmup-related timers if still running (shouldn't be, but safe)
    CancelTimerSafe(g_hCheckTimer);
    CancelTimerSafe(g_hWarmupTimer);

    // ------------------------------------------------------------------
    // Read final CT and T scores from the game
    // ------------------------------------------------------------------
    int ctScore = CS_GetTeamScore(CS_TEAM_CT);
    int tScore  = CS_GetTeamScore(CS_TEAM_T);

    // ------------------------------------------------------------------
    // Map CS:GO teams back to our team1/team2 based on starting sides.
    // g_iTeam1CSTeam is either CS_TEAM_CT or CS_TEAM_T.
    // ------------------------------------------------------------------
    int team1Score, team2Score;
    if (g_iTeam1CSTeam == CS_TEAM_CT)
    {
        // This works for both normal and post-halftime because CS:GetTeamScore
        // returns the cumulative score for whichever side CT is now, but
        // the game tracks by team slot (1/2) not by side, so we need
        // to use the correct team index.
        // For correct results we store team scores by CS team number (1/2).
        team1Score = CS_GetTeamScore(CS_TEAM_CT);
        team2Score = CS_GetTeamScore(CS_TEAM_T);
    }
    else
    {
        team1Score = CS_GetTeamScore(CS_TEAM_T);
        team2Score = CS_GetTeamScore(CS_TEAM_CT);
    }

    // Determine winner
    char winner[8];
    if (team1Score > team2Score)
        strcopy(winner, sizeof(winner), "team1");
    else if (team2Score > team1Score)
        strcopy(winner, sizeof(winner), "team2");
    else
        strcopy(winner, sizeof(winner), "tie");

    LogMessage("[MM-Match] Match over! Team1=%d Team2=%d Winner=%s",
        team1Score, team2Score, winner);

    // ------------------------------------------------------------------
    // Announce result to all players
    // ------------------------------------------------------------------
    MM_PrintToChatAll("\x04Match Over! \x01Team1 \x09%d\x01 - \x09%d\x01 Team2",
        team1Score, team2Score);

    if (StrEqual(winner, "tie"))
        MM_PrintToChatAll("\x07The match ended in a draw!");
    else if (StrEqual(winner, "team1"))
        MM_PrintToChatAll("\x04Team 1 wins the match!");
    else
        MM_PrintToChatAll("\x04Team 2 wins the match!");

    // ------------------------------------------------------------------
    // Persist stats and update mm_matches
    // ------------------------------------------------------------------
    if (g_hDB != null && g_iMatchId > 0)
    {
        // Update match record
        char query[512];
        Format(query, sizeof(query),
            "UPDATE mm_matches SET status='finished', team1_score=%d, team2_score=%d, winner='%s', ended_at=NOW() WHERE id=%d",
            team1Score, team2Score, winner, g_iMatchId);
        g_hDB.Query(CB_GenericQuery, query);

        // Save all player stats (async, threaded)
        SaveAllPlayerStats();
    }

    // ------------------------------------------------------------------
    // Schedule lobby redirect with countdown announcements
    // ------------------------------------------------------------------
    g_iRedirectCountdown = 15;
    CreateTimer(1.0, Timer_CountdownAnnounce, _, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);

    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Timer_CountdownAnnounce — 1-second countdown to redirect
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_CountdownAnnounce(Handle timer)
{
    if (g_iRedirectCountdown <= 0)
    {
        // Fire the actual redirect
        CreateTimer(0.1, Timer_RedirectToLobby);
        g_hCountdownTimer = null;
        return Plugin_Stop;
    }

    // Only announce at certain intervals to avoid chat spam
    if (g_iRedirectCountdown <= 5 || g_iRedirectCountdown % 5 == 0)
    {
        MM_PrintToChatAll("\x09Returning to lobby in \x04%d\x09 second%s...",
            g_iRedirectCountdown,
            g_iRedirectCountdown == 1 ? "" : "s");
    }

    g_iRedirectCountdown--;
    return Plugin_Continue;
}

// ─────────────────────────────────────────────────────────────────────────────
// Timer_RedirectToLobby — connect all clients to the lobby server
// ─────────────────────────────────────────────────────────────────────────────

public Action Timer_RedirectToLobby(Handle timer)
{
    if (g_sLobbyIP[0] == '\0')
    {
        LogError("[MM-Match] Timer_RedirectToLobby: mm_lobby_ip is empty — cannot redirect.");
        MM_PrintToChatAll("\x0CCould not redirect to lobby (no lobby IP configured).");
        return Plugin_Stop;
    }

    MM_PrintToChatAll("\x04Connecting to lobby server...");
    LogMessage("[MM-Match] Redirecting all players to lobby: %s", g_sLobbyIP);

    for (int i = 1; i <= MaxClients; i++)
    {
        if (MM_IsValidClient(i))
        {
            // "connect IP:PORT" drops the player to the specified server
            ClientCommand(i, "connect %s", g_sLobbyIP);
        }
    }

    return Plugin_Stop;
}

// ─────────────────────────────────────────────────────────────────────────────
// SaveAllPlayerStats — write per-player stats to mm_match_players
//
// Issues one threaded UPDATE per connected player to avoid blocking the
// server thread. Each query is independent so order doesn't matter.
// ─────────────────────────────────────────────────────────────────────────────

void SaveAllPlayerStats()
{
    if (g_hDB == null || g_iMatchId <= 0)
        return;

    for (int i = 1; i <= MaxClients; i++)
    {
        // Save stats for any client with a known SteamID (even disconnected)
        if (g_sSteamId[i][0] == '\0')
            continue;

        // Escape the SteamID to prevent SQL injection (it's user-derived)
        char escapedSID[64];
        g_hDB.Escape(g_sSteamId[i], escapedSID, sizeof(escapedSID));

        char query[768];
        Format(query, sizeof(query),
            "UPDATE mm_match_players SET kills=%d, deaths=%d, assists=%d, headshots=%d, mvps=%d, score=%d, damage=%d WHERE match_id=%d AND steam_id='%s'",
            g_iKills[i], g_iDeaths[i], g_iAssists[i], g_iHeadshots[i],
            g_iMVPs[i], g_iScore[i], g_iDamage[i],
            g_iMatchId, escapedSID);

        g_hDB.Query(CB_SaveStats, query, i);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// sm_score command — display current match score in chat
// ─────────────────────────────────────────────────────────────────────────────

public Action Cmd_Score(int client, int args)
{
    if (!MM_IsValidClient(client))
        return Plugin_Handled;

    int ctScore   = CS_GetTeamScore(CS_TEAM_CT);
    int tScore    = CS_GetTeamScore(CS_TEAM_T);
    int team1Score = (g_iTeam1CSTeam == CS_TEAM_CT) ? ctScore : tScore;
    int team2Score = (g_iTeam1CSTeam == CS_TEAM_CT) ? tScore  : ctScore;

    // Approximate current round number from total rounds played
    int roundNum = ctScore + tScore;

    int maxRounds = GetConVarInt(FindConVar("mp_maxrounds"));
    char stateStr[16];
    switch (g_eMatchState)
    {
        case MatchState_Warmup:   strcopy(stateStr, sizeof(stateStr), "Warmup");
        case MatchState_Live:     strcopy(stateStr, sizeof(stateStr), "Live");
        case MatchState_Overtime: strcopy(stateStr, sizeof(stateStr), "Overtime");
        case MatchState_Finished: strcopy(stateStr, sizeof(stateStr), "Finished");
    }

    MM_PrintToChat(client,
        "Score: \x04Team1 %d\x01 - \x04%d Team2\x01 | Round %d/%d | %s",
        team1Score, team2Score, roundNum, maxRounds, stateStr);

    return Plugin_Handled;
}

// ─────────────────────────────────────────────────────────────────────────────
// DB helper: Set mm_matches.status
// ─────────────────────────────────────────────────────────────────────────────

void DB_SetMatchStatus(const char[] status)
{
    if (g_hDB == null || g_iMatchId <= 0)
        return;

    char query[256];
    Format(query, sizeof(query),
        "UPDATE mm_matches SET status='%s' WHERE id=%d",
        status, g_iMatchId);
    g_hDB.Query(CB_GenericQuery, query);
}

// ─────────────────────────────────────────────────────────────────────────────
// DB_QueryTeamSides — determine which CS team (CT/T) team1 started as.
//
// mm_match_players has a `team` column ('team1'/'team2'). We use the match
// record alongside player data to infer starting sides.
//
// Simplified approach: query the first team1 player's CS:GO team assignment
// at match start by checking the `team` column. We store side-assignment
// in the match table via a convention: team1 always starts CT in the DB
// unless the matchmaker specifies otherwise (future enhancement).
//
// For now: default to team1=CT, team2=T, and query DB to confirm.
// ─────────────────────────────────────────────────────────────────────────────

void DB_QueryTeamSides()
{
    if (g_hDB == null || g_iMatchId <= 0)
        return;

    // We default to team1=CT; the query result will override if needed.
    // A future enhancement would store side choice in the match row.
    // For now, the default (team1=CT) is applied; this function is a hook
    // point for that future logic.
    g_iTeam1CSTeam = CS_TEAM_CT;
    g_iTeam2CSTeam = CS_TEAM_T;

    LogMessage("[MM-Match] Team sides: Team1=%s Team2=%s",
        (g_iTeam1CSTeam == CS_TEAM_CT) ? "CT" : "T",
        (g_iTeam2CSTeam == CS_TEAM_CT) ? "CT" : "T");
}

// ─────────────────────────────────────────────────────────────────────────────
// SQL Callbacks
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generic fire-and-forget callback.
 * Logs errors but otherwise ignores results.
 */
public void CB_GenericQuery(Database db, DBResultSet results, const char[] error, any data)
{
    if (db == null || results == null)
        LogError("[MM-Match] DB query error: %s", error);
}

/**
 * Callback for SaveAllPlayerStats() — logs per-player save success/failure.
 * `data` is the client index (1-based).
 */
public void CB_SaveStats(Database db, DBResultSet results, const char[] error, any data)
{
    int client = view_as<int>(data);
    if (db == null || results == null)
    {
        LogError("[MM-Match] Failed to save stats for client %d (%s): %s",
            client, g_sSteamId[client], error);
        return;
    }
    LogMessage("[MM-Match] Stats saved for %s (client %d).", g_sSteamId[client], client);
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper utilities
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Returns true if `steamId` is in the team1 or team2 roster.
 */
bool IsWhitelisted(const char[] steamId)
{
    for (int i = 0; i < g_iTeam1Count; i++)
    {
        if (StrEqual(g_sTeam1SteamIds[i], steamId, false))
            return true;
    }
    for (int i = 0; i < g_iTeam2Count; i++)
    {
        if (StrEqual(g_sTeam2SteamIds[i], steamId, false))
            return true;
    }
    return false;
}

/**
 * Returns true if `client` is a valid, in-bounds client index
 * (does NOT require IsClientInGame — safe to use in pre-connect hooks).
 */
bool IsValidClientIndex(int client)
{
    return (client > 0 && client <= MaxClients);
}

/**
 * Resets all per-client stat arrays to zero and clears SteamID cache.
 */
void ResetAllClientStats()
{
    for (int i = 0; i <= MAXPLAYERS; i++)
    {
        g_iKills[i]      = 0;
        g_iDeaths[i]     = 0;
        g_iAssists[i]    = 0;
        g_iHeadshots[i]  = 0;
        g_iMVPs[i]       = 0;
        g_iDamage[i]     = 0;
        g_iScore[i]      = 0;
        g_sSteamId[i][0] = '\0';
    }
}

/**
 * Safely cancels a timer handle and sets it to null.
 * Avoids double-free errors.
 */
void CancelTimerSafe(Handle &hTimer)
{
    if (hTimer != null)
    {
        KillTimer(hTimer);
        hTimer = null;
    }
}
